libstdc++: Complex Numbers
Complex Numbers
Numerics
Classes
class std::complex< _Tp >
class std::complex< double >
class std::complex< float >
class std::complex< long double >
Functions
constexpr std::complex< float >::complex (const complex< double > &)
constexpr std::complex< float >::complex (const complex< long double > &)
constexpr std::complex< double >::complex (const complex< long double > &)
template<typename _Tp >
_Tp std::__complex_abs (const complex< _Tp > &__z)
template<typename _Tp >
_Tp std::__complex_arg (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_cos (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_cosh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_exp (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_log (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_pow (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
complex< _Tp > std::__complex_pow_unsigned (complex< _Tp > __x, unsigned __n)
template<typename _Tp >
complex< _Tp > std::__complex_sin (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_sinh (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_sqrt (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_tan (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::__complex_tanh (const complex< _Tp > &__z)
template<typename _Tp >
_Tp std::abs (const complex< _Tp > &)
template<typename _Tp >
_Tp std::arg (const complex< _Tp > &)
template<typename _Tp >
std::complex< typename __gnu_cxx::__promote< _Tp >::__type > std::tr1::conj (_Tp __x)
template<typename _Tp >
constexpr complex< _Tp > std::conj (const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::conj (const std::complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::cos (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::cosh (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::exp (const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::fabs (const std::complex< _Tp > &__z)
template<typename _Tp >
constexpr _Tp std::imag (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::log (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::log10 (const complex< _Tp > &)
template<typename _Tp >
_Tp constexpr std::norm (const complex< _Tp > &)
constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const complex< _Up > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator+= (const complex< _Up > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator-= (const complex< _Up > &)
constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const complex< _Up > &)
template<typename _Tp , typename _CharT , class _Traits >
basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > &__os, const complex< _Tp > &__x)
constexpr complex< _Tp > & std::complex< _Tp >::operator= (const _Tp &)
template<typename _Up >
constexpr complex< _Tp > & std::complex< _Tp >::operator= (const complex< _Up > &)
template<typename _Tp , typename _CharT , class _Traits >
basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > &__is, complex< _Tp > &__x)
template<typename _Tp >
complex< _Tp > std::polar (const _Tp &, const _Tp &=0)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::polar (const _Tp &__rho, const _Up &__theta)
template<typename _Tp >
complex< _Tp > std::pow (const _Tp &, const complex< _Tp > &)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const _Tp &__x, const std::complex< _Tp > &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const _Tp &__x, const std::complex< _Up > &__y)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, const _Tp &)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::pow (const complex< _Tp > &, int)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > &__x, const _Up &__y)
template<typename _Tp >
std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > &__x, const std::complex< _Tp > &__y)
template<typename _Tp , typename _Up >
std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > &__x, const std::complex< _Up > &__y)
template<typename _Tp >
constexpr _Tp std::real (const complex< _Tp > &__z)
template<typename _Tp >
complex< _Tp > std::sin (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::sinh (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::sqrt (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::tan (const complex< _Tp > &)
template<typename _Tp >
complex< _Tp > std::tanh (const complex< _Tp > &)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator+ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator- (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator* (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const complex< _Tp > &__x, const _Tp &__y)
template<typename _Tp >
constexpr complex< _Tp > std::operator/ (const _Tp &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool std::operator== (const complex< _Tp > &__x, const complex< _Tp > &__y)
template<typename _Tp >
constexpr bool std::operator== (const complex< _Tp > &__x, const _Tp &__y)
Detailed Description
Classes and functions for complex numbers.
Function Documentation
complex() [1/3]
constexpr std::complex< float >::complex (const complex< double > & __z) inline explicit constexpr
Definition at line 1973 of file complex.
complex() [2/3]
constexpr std::complex< float >::complex (const complex< long double > & __z) inline explicit constexpr
Definition at line 1977 of file complex.
complex() [3/3]
constexpr std::complex< double >::complex (const complex< long double > & __z) inline explicit constexpr
Definition at line 1981 of file complex.
__complex_abs()
template<typename _Tp > _Tp std::__complex_abs (const complex< _Tp > & __z) inline
Definition at line 862 of file complex.
__complex_arg()
template<typename _Tp > _Tp std::__complex_arg (const complex< _Tp > & __z) inline
Definition at line 898 of file complex.
__complex_cos()
template<typename _Tp > complex< _Tp > std::__complex_cos (const complex< _Tp > & __z) inline
Definition at line 978 of file complex.
__complex_cosh()
template<typename _Tp > complex< _Tp > std::__complex_cosh (const complex< _Tp > & __z) inline
Definition at line 1008 of file complex.
__complex_exp()
template<typename _Tp > complex< _Tp > std::__complex_exp (const complex< _Tp > & __z) inline
Definition at line 1038 of file complex.
__complex_log()
template<typename _Tp > complex< _Tp > std::__complex_log (const complex< _Tp > & __z) inline
Definition at line 1065 of file complex.
__complex_pow()
template<typename _Tp > complex< _Tp > std::__complex_pow (const complex< _Tp > & __x, const complex< _Tp > & __y) inline
Definition at line 1304 of file complex.
__complex_pow_unsigned()
template<typename _Tp > complex< _Tp > std::__complex_pow_unsigned (complex< _Tp > __x, unsigned __n)
Definition at line 1258 of file complex.
__complex_sin()
template<typename _Tp > complex< _Tp > std::__complex_sin (const complex< _Tp > & __z) inline
Definition at line 1096 of file complex.
__complex_sinh()
template<typename _Tp > complex< _Tp > std::__complex_sinh (const complex< _Tp > & __z) inline
Definition at line 1126 of file complex.
__complex_sqrt()
template<typename _Tp > complex< _Tp > std::__complex_sqrt (const complex< _Tp > & __z)
Definition at line 1157 of file complex.
__complex_tan()
template<typename _Tp > complex< _Tp > std::__complex_tan (const complex< _Tp > & __z) inline
Definition at line 1201 of file complex.
__complex_tanh()
template<typename _Tp > complex< _Tp > std::__complex_tanh (const complex< _Tp > & __z) inline
Definition at line 1229 of file complex.
abs()
template<typename _Tp > _Tp std::abs (const complex< _Tp > & __z) inline
Return magnitude of z.
Definition at line 891 of file complex.
Referenced by std::chrono::abs(), std::binomial_distribution< _IntType >::operator()(), and std::poisson_distribution< _IntType >::operator()().
arg()
template<typename _Tp > _Tp std::arg (const complex< _Tp > & __z) inline
Return phase angle of z.
Definition at line 918 of file complex.
conj() [1/3]
template<typename _Tp > std::complex< typename __gnu_cxx::__promote< _Tp >::__type > std::tr1::conj (_Tp __x) inline
Definition at line 384 of file tr1/complex.
conj() [2/3]
template<typename _Tp > constexpr complex< _Tp > std::conj (const complex< _Tp > & __z) inline constexpr
Return complex conjugate of z.
Definition at line 970 of file complex.
conj() [3/3]
template<typename _Tp > std::complex< _Tp > std::tr1::conj (const std::complex< _Tp > & __z) inline
Definition at line 379 of file tr1/complex.
cos()
template<typename _Tp > complex< _Tp > std::cos (const complex< _Tp > & __z) inline
Return complex cosine of z.
Definition at line 1002 of file complex.
cosh()
template<typename _Tp > complex< _Tp > std::cosh (const complex< _Tp > & __z) inline
Return complex hyperbolic cosine of z.
Definition at line 1032 of file complex.
exp()
template<typename _Tp > complex< _Tp > std::exp (const complex< _Tp > & __z) inline
Return complex base e exponential of z.
Definition at line 1058 of file complex.
fabs()
template<typename _Tp > std::complex< _Tp > std::tr1::fabs (const std::complex< _Tp > & __z) inline
fabs(__z) [8.1.8].
Definition at line 311 of file tr1/complex.
imag()
template<typename _Tp > constexpr _Tp std::imag (const complex< _Tp > & __z) constexpr
Definition at line 577 of file complex.
log()
template<typename _Tp > complex< _Tp > std::log (const complex< _Tp > & __z) inline
Return complex natural logarithm of z.
Definition at line 1085 of file complex.
Referenced by std::generate_canonical(), std::normal_distribution< _RealType >::operator()(), std::gamma_distribution< _RealType >::operator()(), std::binomial_distribution< _IntType >::operator()(), std::poisson_distribution< _IntType >::operator()(), std::operator<<(), std::operator<<(), and std::operator<<().
log10()
template<typename _Tp > complex< _Tp > std::log10 (const complex< _Tp > & __z) inline
Return complex base 10 logarithm of z.
Definition at line 1090 of file complex.
norm()
template<typename _Tp > _Tp constexpr std::norm (const complex< _Tp > & __z) inline constexpr
Return z magnitude squared.
Definition at line 954 of file complex.
operator*() [1/3]
template<typename _Tp > constexpr complex< _Tp > std::operator* (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x times y.
Definition at line 413 of file complex.
operator*() [2/3]
template<typename _Tp > constexpr complex< _Tp > std::operator* (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x times y.
Definition at line 404 of file complex.
operator*() [3/3]
template<typename _Tp > constexpr complex< _Tp > std::operator* (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x times y.
Definition at line 395 of file complex.
operator*=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const _Tp & __t) constexpr
Multiply this complex number by a scalar.
Definition at line 254 of file complex.
operator*=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator*= (const complex< _Up > & __z) constexpr
Multiply this complex number by another.
Definition at line 308 of file complex.
operator+() [1/4]
template<typename _Tp > constexpr complex< _Tp > std::operator+ (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x plus y.
Definition at line 353 of file complex.
operator+() [2/4]
template<typename _Tp > constexpr complex< _Tp > std::operator+ (const complex< _Tp > & __x) inline constexpr
Return x.
Definition at line 454 of file complex.
operator+() [3/4]
template<typename _Tp > constexpr complex< _Tp > std::operator+ (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x plus y.
Definition at line 344 of file complex.
operator+() [4/4]
template<typename _Tp > constexpr complex< _Tp > std::operator+ (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x plus y.
Definition at line 335 of file complex.
operator+=()
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator+= (const complex< _Up > & __z) constexpr
Add another complex number to this one.
Definition at line 285 of file complex.
operator-() [1/4]
template<typename _Tp > constexpr complex< _Tp > std::operator- (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x minus y.
Definition at line 383 of file complex.
operator-() [2/4]
template<typename _Tp > constexpr complex< _Tp > std::operator- (const complex< _Tp > & __x) inline constexpr
Return complex negation of x.
Definition at line 460 of file complex.
operator-() [3/4]
template<typename _Tp > constexpr complex< _Tp > std::operator- (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x minus y.
Definition at line 374 of file complex.
operator-() [4/4]
template<typename _Tp > constexpr complex< _Tp > std::operator- (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x minus y.
Definition at line 365 of file complex.
operator-=()
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator-= (const complex< _Up > & __z) constexpr
Subtract another complex number from this one.
Definition at line 296 of file complex.
operator/() [1/3]
template<typename _Tp > constexpr complex< _Tp > std::operator/ (const _Tp & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 443 of file complex.
operator/() [2/3]
template<typename _Tp > constexpr complex< _Tp > std::operator/ (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 434 of file complex.
operator/() [3/3]
template<typename _Tp > constexpr complex< _Tp > std::operator/ (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return new complex value x divided by y.
Definition at line 425 of file complex.
operator/=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const _Tp & __t) constexpr
Divide this complex number by a scalar.
Definition at line 264 of file complex.
operator/=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator/= (const complex< _Up > & __z) constexpr
Divide this complex number by another.
Definition at line 321 of file complex.
operator<<()
template<typename _Tp , typename _CharT , class _Traits > basic_ostream< _CharT, _Traits > & std::operator<< (basic_ostream< _CharT, _Traits > & __os, const complex< _Tp > & __x)
Insertion operator for complex values.
Definition at line 504 of file complex.
operator=() [1/2]
template<typename _Tp > constexpr complex< _Tp > & std::complex< _Tp >::operator= (const _Tp & __t) constexpr
Assign a scalar to this complex number.
Definition at line 244 of file complex.
operator=() [2/2]
template<typename _Tp > template<typename _Up > constexpr complex< _Tp > & std::complex< _Tp >::operator= (const complex< _Up > & __z) constexpr
Assign another complex number to this one.
Definition at line 274 of file complex.
operator==() [1/2]
template<typename _Tp > constexpr bool std::operator== (const complex< _Tp > & __x, const _Tp & __y) inline constexpr
Return true if x is equal to y.
Definition at line 472 of file complex.
operator==() [2/2]
template<typename _Tp > constexpr bool std::operator== (const complex< _Tp > & __x, const complex< _Tp > & __y) inline constexpr
Return true if x is equal to y.
Definition at line 467 of file complex.
operator>>()
template<typename _Tp , typename _CharT , class _Traits > basic_istream< _CharT, _Traits > & std::operator>> (basic_istream< _CharT, _Traits > & __is, complex< _Tp > & __x)
Extraction operator for complex values.
Definition at line 504 of file complex.
polar() [1/2]
template<typename _Tp > complex< _Tp > std::polar (const _Tp & __rho, const _Tp & __theta = 0) inline
Return complex with magnitude rho and angle theta.
Definition at line 962 of file complex.
polar() [2/2]
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::polar (const _Tp & __rho, const _Up & __theta) inline
Definition at line 393 of file tr1/complex.
pow() [1/10]
template<typename _Tp > complex< _Tp > std::pow (const _Tp & __x, const complex< _Tp > & __y) inline
Return x to the y'th power.
Definition at line 1334 of file complex.
pow() [2/10]
template<typename _Tp > std::complex< _Tp > std::tr1::pow (const _Tp & __x, const std::complex< _Tp > & __y) inline
Definition at line 408 of file tr1/complex.
pow() [3/10]
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const _Tp & __x, const std::complex< _Up > & __y) inline
Definition at line 360 of file tr1/complex.
pow() [4/10]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const _Tp & __y)
Return x to the y'th power.
Definition at line 1289 of file complex.
pow() [5/10]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __x, const complex< _Tp > & __y) inline
Return x to the y'th power.
Definition at line 1328 of file complex.
pow() [6/10]
template<typename _Tp > complex< _Tp > std::pow (const complex< _Tp > & __z, int __n) inline
Return x to the y'th power.
Definition at line 1280 of file complex.
Referenced by std::gamma_distribution< _RealType >::operator()(), and std::operator<<().
pow() [7/10]
template<typename _Tp > std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > & __x, const _Tp & __y) inline
Definition at line 403 of file tr1/complex.
pow() [8/10]
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > & __x, const _Up & __y) inline
Additional overloads [8.1.9].
Definition at line 352 of file tr1/complex.
pow() [9/10]
template<typename _Tp > std::complex< _Tp > std::tr1::pow (const std::complex< _Tp > & __x, const std::complex< _Tp > & __y) inline
Definition at line 413 of file tr1/complex.
pow() [10/10]
template<typename _Tp , typename _Up > std::complex< typename __gnu_cxx::__promote_2< _Tp, _Up >::__type > std::tr1::pow (const std::complex< _Tp > & __x, const std::complex< _Up > & __y) inline
Definition at line 368 of file tr1/complex.
real()
template<typename _Tp > constexpr _Tp std::real (const complex< _Tp > & __z) constexpr
Definition at line 572 of file complex.
sin()
template<typename _Tp > complex< _Tp > std::sin (const complex< _Tp > & __z) inline
Return complex sine of z.
Definition at line 1120 of file complex.
sinh()
template<typename _Tp > complex< _Tp > std::sinh (const complex< _Tp > & __z) inline
Return complex hyperbolic sine of z.
Definition at line 1150 of file complex.
sqrt()
template<typename _Tp > complex< _Tp > std::sqrt (const complex< _Tp > & __z) inline
Return complex square root of z.
Definition at line 1194 of file complex.
Referenced by std::student_t_distribution< _RealType >::operator()(), and std::normal_distribution< _RealType >::operator()().
tan()
template<typename _Tp > complex< _Tp > std::tan (const complex< _Tp > & __z) inline
Return complex tangent of z.
Definition at line 1221 of file complex.
Referenced by std::operator<<().
tanh()
template<typename _Tp > complex< _Tp > std::tanh (const complex< _Tp > & __z) inline
Return complex hyperbolic tangent of z.
Definition at line 1249 of file complex.