libstdc++: Random Number Generation
Random Number Generation
Numerics
Modules
Random Number Distributions
Random Number Generators
Random Number Utilities
Functions
template<typename _RealType , size_t __bits, typename _UniformRandomNumberGenerator >
_RealType std::generate_canonical (_UniformRandomNumberGenerator &__g)
Detailed Description
A facility for generating random numbers on selected distributions.
Function Documentation
generate_canonical()
template<typename _RealType , size_t __bits, typename _UniformRandomNumberGenerator > _RealType std::generate_canonical (_UniformRandomNumberGenerator & __g)
A function template for converting the output of a (integral) uniform random number generator to a floatng point result in the range [0-1).
Definition at line 3346 of file bits/random.tcc.
References std::numeric_limits< _Tp >::epsilon(), std::generate_canonical(), std::log(), and std::min().
Referenced by std::generate_canonical().