libstdc++: __gnu_cxx Namespace Reference
__gnu_cxx Namespace Reference
Extensions
Namespaces
namespace __detail
namespace typelist
Classes
struct __alloc_traits
struct __common_pool_policy
class __mt_alloc
class __mt_alloc_base
struct __per_type_pool_policy
class __pool
class __pool< false >
class __pool< true >
class __pool_alloc
class __pool_alloc_base
struct __pool_base
class __rc_string_base
class __scoped_lock
class __versa_string
struct _Caster
struct _Char_types
class _ExtPtr_allocator
struct _Invalid_type
class _Pointer_adapter
class _Relative_pointer_impl
class _Relative_pointer_impl< const _Tp >
class _Std_pointer_impl
struct _Unqualified_type
struct annotate_base
class binary_compose
class bitmap_allocator
struct char_traits
struct character
struct condition_base
struct constant_binary_fun
struct constant_unary_fun
struct constant_void_fun
class debug_allocator
class enc_filebuf
struct encoding_char_traits
class encoding_state
struct forced_error
class free_list
class hash_map
class hash_multimap
class hash_multiset
class hash_set
struct limit_condition
class malloc_allocator
class new_allocator
struct project1st
struct project2nd
struct random_condition
struct rb_tree
class rope
struct select1st
struct select2nd
class slist
class stdio_filebuf
class stdio_sync_filebuf
class subtractive_rng
struct temporary_buffer
class throw_allocator_base
struct throw_allocator_limit
struct throw_allocator_random
struct throw_value_base
struct throw_value_limit
struct throw_value_random
class unary_compose
Typedefs
typedef void(* __destroy_handler) (void *)
template<typename _Tp >
using __int_traits = __numeric_traits_integer< _Tp >
typedef __versa_string< char, std::char_traits< char >, std::allocator< char >, __rc_string_base > __rc_string
typedef __vstring __sso_string
typedef __versa_string< char16_t, std::char_traits< char16_t >, std::allocator< char16_t >, __rc_string_base > __u16rc_string
typedef __u16vstring __u16sso_string
typedef __versa_string< char16_t > __u16vstring
typedef __versa_string< char32_t, std::char_traits< char32_t >, std::allocator< char32_t >, __rc_string_base > __u32rc_string
typedef __u32vstring __u32sso_string
typedef __versa_string< char32_t > __u32vstring
typedef __versa_string< char > __vstring
typedef __versa_string< wchar_t, std::char_traits< wchar_t >, std::allocator< wchar_t >, __rc_string_base > __wrc_string
typedef __wvstring __wsso_string
typedef __versa_string< wchar_t > __wvstring
typedef rope< char > crope
typedef rope< wchar_t > wrope
Enumerations
enum { _S_num_primes }
enum _Lock_policy { _S_single , _S_mutex , _S_atomic }
Functions
void __atomic_add (volatile _Atomic_word *, int) noexcept
void __atomic_add_dispatch (_Atomic_word *__mem, int __val)
void __atomic_add_single (_Atomic_word *__mem, int __val)
template<class _Tp >
void __aux_require_boolean_expr (const _Tp &__t)
template<typename _ToType , typename _FromType >
_ToType __const_pointer_cast (_FromType *__arg)
template<typename _ToType , typename _FromType >
_ToType __const_pointer_cast (const _FromType &__arg)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
std::pair< _InputIterator, _OutputIterator > __copy_n (_InputIterator __first, _Size __count, _OutputIterator __result, std::input_iterator_tag)
template<typename _RAIterator , typename _Size , typename _OutputIterator >
std::pair< _RAIterator, _OutputIterator > __copy_n (_RAIterator __first, _Size __count, _OutputIterator __result, std::random_access_iterator_tag)
template<typename _InputIterator , typename _Distance >
void __distance (_InputIterator __first, _InputIterator __last, _Distance &__n, std::input_iterator_tag)
template<typename _RandomAccessIterator , typename _Distance >
void __distance (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance &__n, std::random_access_iterator_tag)
template<typename _ToType , typename _FromType >
_ToType __dynamic_pointer_cast (_FromType *__arg)
template<typename _ToType , typename _FromType >
_ToType __dynamic_pointer_cast (const _FromType &__arg)
void __error_type_must_be_a_signed_integer_type ()
void __error_type_must_be_an_integer_type ()
void __error_type_must_be_an_unsigned_integer_type ()
_Atomic_word __exchange_and_add (volatile _Atomic_word *, int) noexcept
_Atomic_word __exchange_and_add_dispatch (_Atomic_word *__mem, int __val)
_Atomic_word __exchange_and_add_single (_Atomic_word *__mem, int __val)
template<class _Concept >
constexpr void __function_requires ()
template<typename _Type >
constexpr bool __is_null_pointer (_Type *__ptr)
template<typename _Type >
constexpr bool __is_null_pointer (_Type)
constexpr bool __is_null_pointer (std::nullptr_t)
bool __is_single_threaded () noexcept
template<typename _InputIterator1 , typename _InputIterator2 >
int __lexicographical_compare_3way (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
int __lexicographical_compare_3way (const char *__first1, const char *__last1, const char *__first2, const char *__last2)
int __lexicographical_compare_3way (const unsigned char *__first1, const unsigned char *__last1, const unsigned char *__first2, const unsigned char *__last2)
template<typename _Tp >
const _Tp & __median (const _Tp &__a, const _Tp &__b, const _Tp &__c)
template<typename _Tp , typename _Compare >
const _Tp & __median (const _Tp &__a, const _Tp &__b, const _Tp &__c, _Compare __comp)
crope::reference __mutable_reference_at (crope &__c, std::size_t __i)
template<typename _Tp , typename _Integer >
_Tp __power (_Tp __x, _Integer __n)
template<typename _Tp , typename _Integer , typename _MonoidOperation >
_Tp __power (_Tp __x, _Integer __n, _MonoidOperation __monoid_op)
template<typename _InputIterator , typename _RandomAccessIterator , typename _RandomNumberGenerator , typename _Distance >
_RandomAccessIterator __random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out, _RandomNumberGenerator &__rand, const _Distance __n)
template<typename _InputIterator , typename _RandomAccessIterator , typename _Distance >
_RandomAccessIterator __random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out, const _Distance __n)
template<typename _ToType , typename _FromType >
_ToType __reinterpret_pointer_cast (_FromType *__arg)
template<typename _ToType , typename _FromType >
_ToType __reinterpret_pointer_cast (const _FromType &__arg)
_Slist_node_base * __slist_make_link (_Slist_node_base *__prev_node, _Slist_node_base *__new_node)
_Slist_node_base * __slist_previous (_Slist_node_base *__head, const _Slist_node_base *__node)
const _Slist_node_base * __slist_previous (const _Slist_node_base *__head, const _Slist_node_base *__node)
_Slist_node_base * __slist_reverse (_Slist_node_base *__node)
std::size_t __slist_size (_Slist_node_base *__node)
void __slist_splice_after (_Slist_node_base *__pos, _Slist_node_base *__before_first, _Slist_node_base *__before_last)
void __slist_splice_after (_Slist_node_base *__pos, _Slist_node_base *__head)
template<typename _ToType , typename _FromType >
_ToType __static_pointer_cast (_FromType *__arg)
template<typename _ToType , typename _FromType >
_ToType __static_pointer_cast (const _FromType &__arg)
size_t __stl_hash_string (const char *__s)
unsigned long __stl_next_prime (unsigned long __n)
template<typename _TRet , typename _Ret = _TRet, typename _CharT , typename... _Base>
_Ret __stoa (_TRet(*__convf)(const _CharT *, _CharT **, _Base...), const char *__name, const _CharT *__str, std::size_t *__idx, _Base... __base)
void __throw_concurrence_lock_error ()
void __throw_concurrence_unlock_error ()
void __throw_forced_error ()
template<typename _String , typename _CharT = typename _String::value_type>
_String __to_xstring (int(*__convf)(_CharT *, std::size_t, const _CharT *, __builtin_va_list), std::size_t __n, const _CharT *__fmt,...)
template<typename _InputIter , typename _Size , typename _ForwardIter >
std::pair< _InputIter, _ForwardIter > __uninitialized_copy_n (_InputIter __first, _Size __count, _ForwardIter __result)
template<typename _InputIter , typename _Size , typename _ForwardIter >
std::pair< _InputIter, _ForwardIter > __uninitialized_copy_n (_InputIter __first, _Size __count, _ForwardIter __result, std::input_iterator_tag)
template<typename _RandomAccessIter , typename _Size , typename _ForwardIter >
std::pair< _RandomAccessIter, _ForwardIter > __uninitialized_copy_n (_RandomAccessIter __first, _Size __count, _ForwardIter __result, std::random_access_iterator_tag)
template<typename _InputIter , typename _Size , typename _ForwardIter , typename _Allocator >
std::pair< _InputIter, _ForwardIter > __uninitialized_copy_n_a (_InputIter __first, _Size __count, _ForwardIter __result, _Allocator __alloc)
template<typename _InputIter , typename _Size , typename _ForwardIter , typename _Tp >
std::pair< _InputIter, _ForwardIter > __uninitialized_copy_n_a (_InputIter __first, _Size __count, _ForwardIter __result, std::allocator< _Tp >)
void __verbose_terminate_handler ()
std::size_t _Bit_scan_forward (std::size_t __num)
template<typename _ForwardIterator , typename _Allocator >
void _Destroy_const (_ForwardIterator __first, _ForwardIterator __last, _Allocator __alloc)
template<typename _ForwardIterator , typename _Tp >
void _Destroy_const (_ForwardIterator __first, _ForwardIterator __last, std::allocator< _Tp >)
template<class _CharT , class _Traits >
void _Rope_fill (std::basic_ostream< _CharT, _Traits > &__o, std::size_t __n)
template<class _CharT >
bool _Rope_is_simple (_CharT *)
bool _Rope_is_simple (char *)
bool _Rope_is_simple (wchar_t *)
template<class _Rope_iterator >
void _Rope_rotate (_Rope_iterator __first, _Rope_iterator __middle, _Rope_iterator __last)
template<class _CharT >
void _S_cond_store_eos (_CharT &)
void _S_cond_store_eos (char &__c)
void _S_cond_store_eos (wchar_t &__c)
template<class _CharT >
_CharT _S_eos (_CharT *)
template<class _CharT >
bool _S_is_basic_char_type (_CharT *)
bool _S_is_basic_char_type (char *)
bool _S_is_basic_char_type (wchar_t *)
template<class _CharT >
bool _S_is_one_byte_char_type (_CharT *)
bool _S_is_one_byte_char_type (char *)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type airy_ai (_Tp __x)
float airy_aif (float __x)
long double airy_ail (long double __x)
template<typename _Tp >
__gnu_cxx::__promote< _Tp >::__type airy_bi (_Tp __x)
float airy_bif (float __x)
long double airy_bil (long double __x)
template<class _Operation1 , class _Operation2 >
unary_compose< _Operation1, _Operation2 > compose1 (const _Operation1 &__fn1, const _Operation2 &__fn2)
template<class _Operation1 , class _Operation2 , class _Operation3 >
binary_compose< _Operation1, _Operation2, _Operation3 > compose2 (const _Operation1 &__fn1, const _Operation2 &__fn2, const _Operation3 &__fn3)
template<typename _Tpa , typename _Tpc , typename _Tp >
__gnu_cxx::__promote_3< _Tpa, _Tpc, _Tp >::__type conf_hyperg (_Tpa __a, _Tpc __c, _Tp __x)
float conf_hypergf (float __a, float __c, float __x)
long double conf_hypergl (long double __a, long double __c, long double __x)
template<class _Result >
constant_void_fun< _Result > constant0 (const _Result &__val)
template<class _Result >
constant_unary_fun< _Result, _Result > constant1 (const _Result &__val)
template<class _Result >
constant_binary_fun< _Result, _Result, _Result > constant2 (const _Result &__val)
template<typename _InputIterator , typename _Size , typename _OutputIterator >
std::pair< _InputIterator, _OutputIterator > copy_n (_InputIterator __first, _Size __count, _OutputIterator __result)
template<typename _InputIterator , typename _Tp , typename _Size >
void count (_InputIterator __first, _InputIterator __last, const _Tp &__value, _Size &__n)
template<typename _InputIterator , typename _Predicate , typename _Size >
void count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, _Size &__n)
template<typename _InputIterator , typename _Distance >
void distance (_InputIterator __first, _InputIterator __last, _Distance &__n)
template<typename _Tpa , typename _Tpb , typename _Tpc , typename _Tp >
__gnu_cxx::__promote_4< _Tpa, _Tpb, _Tpc, _Tp >::__type hyperg (_Tpa __a, _Tpb __b, _Tpc __c, _Tp __x)
float hypergf (float __a, float __b, float __c, float __x)
long double hypergl (long double __a, long double __b, long double __c, long double __x)
template<class _Tp >
_Tp identity_element (std::multiplies< _Tp >)
template<class _Tp >
_Tp identity_element (std::plus< _Tp >)
template<typename _InputIterator1 , typename _InputIterator2 >
int lexicographical_compare_3way (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
template<class _Ret , class _Tp , class _Arg >
std::const_mem_fun1_t< _Ret, _Tp, _Arg > mem_fun1 (_Ret(_Tp::*__f)(_Arg) const)
template<class _Ret , class _Tp , class _Arg >
std::mem_fun1_t< _Ret, _Tp, _Arg > mem_fun1 (_Ret(_Tp::*__f)(_Arg))
template<class _Ret , class _Tp , class _Arg >
std::const_mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun1_ref (_Ret(_Tp::*__f)(_Arg) const)
template<class _Ret , class _Tp , class _Arg >
std::mem_fun1_ref_t< _Ret, _Tp, _Arg > mem_fun1_ref (_Ret(_Tp::*__f)(_Arg))
template<typename _Tp1 , typename _Tp2 >
bool operator!= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<typename _Iterator , typename _Container >
constexpr bool operator!= (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
constexpr bool operator!= (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator!= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator!= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator!= (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
bool operator!= (const _Pointer_adapter< _Tp > &__lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp >
bool operator!= (const _Pointer_adapter< _Tp > &__lhs, int __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator!= (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator!= (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator!= (const _Rope_char_ptr_proxy< _CharT, _Alloc > &__x, const _Rope_char_ptr_proxy< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator!= (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator!= (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc >
bool operator!= (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)
template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc >
bool operator!= (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm2)
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc >
bool operator!= (const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs1, const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Value , class _HashFcn , class _EqualKey , class _Alloc >
bool operator!= (const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > &__hs1, const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Val , class _Key , class _HF , class _Ex , class _Eq , class _All >
bool operator!= (const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > &__ht1, const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > &__ht2)
template<class _CharT , class _Alloc >
bool operator!= (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)
template<class _Tp , class _Alloc >
bool operator!= (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _Tp >
bool operator!= (int __lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Cond >
throw_value_base< _Cond > operator* (const throw_value_base< _Cond > &__a, const throw_value_base< _Cond > &__b)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > &&__lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > &&__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > &&__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > &&__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (_CharT __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (_CharT __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, _CharT __rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const _CharT *__lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > &&__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
__versa_string< _CharT, _Traits, _Alloc, _Base > operator+ (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<class _CharT , class _Alloc >
_Rope_const_iterator< _CharT, _Alloc > operator+ (const _Rope_const_iterator< _CharT, _Alloc > &__x, std::ptrdiff_t __n)
template<class _CharT , class _Alloc >
_Rope_iterator< _CharT, _Alloc > operator+ (const _Rope_iterator< _CharT, _Alloc > &__x, std::ptrdiff_t __n)
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > operator+ (const rope< _CharT, _Alloc > &__left, _CharT __right)
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > operator+ (const rope< _CharT, _Alloc > &__left, const _CharT *__right)
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > operator+ (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)
template<typename _Cond >
throw_value_base< _Cond > operator+ (const throw_value_base< _Cond > &__a, const throw_value_base< _Cond > &__b)
template<class _CharT , class _Alloc >
_Rope_const_iterator< _CharT, _Alloc > operator+ (std::ptrdiff_t __n, const _Rope_const_iterator< _CharT, _Alloc > &__x)
template<class _CharT , class _Alloc >
_Rope_iterator< _CharT, _Alloc > operator+ (std::ptrdiff_t __n, const _Rope_iterator< _CharT, _Alloc > &__x)
template<typename _Iterator , typename _Container >
constexpr __normal_iterator< _Iterator, _Container > operator+ (typename __normal_iterator< _Iterator, _Container >::difference_type __n, const __normal_iterator< _Iterator, _Container > &__i) noexcept
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > & operator+= (rope< _CharT, _Alloc > &__left, _CharT __right)
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > & operator+= (rope< _CharT, _Alloc > &__left, const _CharT *__right)
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > & operator+= (rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)
template<typename _Iterator , typename _Container >
constexpr __normal_iterator< _Iterator, _Container >::difference_type operator- (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
constexpr auto operator- (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept -> decltype(__lhs.base() - __rhs.base())
template<class _CharT , class _Alloc >
std::ptrdiff_t operator- (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
_Rope_const_iterator< _CharT, _Alloc > operator- (const _Rope_const_iterator< _CharT, _Alloc > &__x, std::ptrdiff_t __n)
template<class _CharT , class _Alloc >
std::ptrdiff_t operator- (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
_Rope_iterator< _CharT, _Alloc > operator- (const _Rope_iterator< _CharT, _Alloc > &__x, std::ptrdiff_t __n)
template<typename _Cond >
throw_value_base< _Cond > operator- (const throw_value_base< _Cond > &__a, const throw_value_base< _Cond > &__b)
template<typename _Tp1 , typename _Tp2 >
bool operator< (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<typename _Iterator , typename _Container >
constexpr bool operator< (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
bool operator< (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator< (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator< (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator< (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator< (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator< (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator< (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator< (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<typename _Value , typename _Int , typename _St >
bool operator< (const character< _Value, _Int, _St > &lhs, const character< _Value, _Int, _St > &rhs)
template<class _CharT , class _Alloc >
bool operator< (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)
template<class _Tp , class _Alloc >
bool operator< (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _Cond >
bool operator< (const throw_value_base< _Cond > &__a, const throw_value_base< _Cond > &__b)
template<class _CharT , class _Traits , class _Alloc >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__o, const rope< _CharT, _Alloc > &__r)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::beta_distribution< _RealType > &__x)
template<typename _UIntType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::hypergeometric_distribution< _UIntType > &__x)
template<size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > &__x)
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4, typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::triangular_distribution< _RealType > &__x)
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::uniform_inside_sphere_distribution< _Dimen, _RealType > &__x)
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::uniform_on_sphere_distribution< _Dimen, _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const __gnu_cxx::von_mises_distribution< _RealType > &__x)
template<typename _CharT , typename _Traits , typename _StoreT >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const _Pointer_adapter< _StoreT > &__p)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const arcsine_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const hoyt_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const k_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const logistic_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const nakagami_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const pareto_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const rice_distribution< _RealType > &__x)
std::ostream & operator<< (std::ostream &os, const annotate_base &__b)
template<typename _Tp1 , typename _Tp2 >
bool operator<= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<typename _Iterator , typename _Container >
constexpr bool operator<= (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
bool operator<= (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator<= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator<= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator<= (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
bool operator<= (const _Pointer_adapter< _Tp > &__lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator<= (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator<= (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator<= (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator<= (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator<= (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)
template<class _Tp , class _Alloc >
bool operator<= (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _Tp1 , typename _Tp2 >
bool operator== (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<size_t _Dimen, typename _RealType >
bool operator== (const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > &__d1, const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > &__d2)
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4>
bool operator== (const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > &__lhs, const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > &__rhs)
template<typename _Tp , typename _Poolp >
bool operator== (const __mt_alloc< _Tp, _Poolp > &, const __mt_alloc< _Tp, _Poolp > &)
template<typename _Iterator , typename _Container >
constexpr bool operator== (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
constexpr bool operator== (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _Tp >
bool operator== (const __pool_alloc< _Tp > &, const __pool_alloc< _Tp > &)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator== (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator== (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator== (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
bool operator== (const _Pointer_adapter< _Tp > &__lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp >
bool operator== (const _Pointer_adapter< _Tp > &__lhs, int __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator== (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator== (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator== (const _Rope_char_ptr_proxy< _CharT, _Alloc > &__x, const _Rope_char_ptr_proxy< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator== (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator== (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<typename _Tp1 , typename _Tp2 >
bool operator== (const bitmap_allocator< _Tp1 > &, const bitmap_allocator< _Tp2 > &) throw ()
template<typename _Value , typename _Int , typename _St >
bool operator== (const character< _Value, _Int, _St > &lhs, const character< _Value, _Int, _St > &rhs)
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc >
bool operator== (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)
template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc >
bool operator== (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > &__hm2)
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc >
bool operator== (const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs1, const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Value , class _HashFcn , class _EqualKey , class _Alloc >
bool operator== (const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > &__hs1, const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Val , class _Key , class _HF , class _Ex , class _Eq , class _All >
bool operator== (const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > &__ht1, const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > &__ht2)
template<class _CharT , class _Alloc >
bool operator== (const rope< _CharT, _Alloc > &__left, const rope< _CharT, _Alloc > &__right)
template<class _Tp , class _Alloc >
bool operator== (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _Tp , typename _Cond >
bool operator== (const throw_allocator_base< _Tp, _Cond > &, const throw_allocator_base< _Tp, _Cond > &)
template<typename _Cond >
bool operator== (const throw_value_base< _Cond > &__a, const throw_value_base< _Cond > &__b)
template<typename _Tp >
bool operator== (int __lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator> (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<typename _Iterator , typename _Container >
constexpr bool operator> (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
bool operator> (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator> (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator> (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator> (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
bool operator> (const _Pointer_adapter< _Tp > &__lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator> (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator> (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator> (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator> (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator> (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)
template<class _Tp , class _Alloc >
bool operator> (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _Tp1 , typename _Tp2 >
bool operator>= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<typename _Iterator , typename _Container >
constexpr bool operator>= (const __normal_iterator< _Iterator, _Container > &__lhs, const __normal_iterator< _Iterator, _Container > &__rhs) noexcept
template<typename _IteratorL , typename _IteratorR , typename _Container >
bool operator>= (const __normal_iterator< _IteratorL, _Container > &__lhs, const __normal_iterator< _IteratorR, _Container > &__rhs) noexcept
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator>= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator>= (const __versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, const _CharT *__rhs)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
bool operator>= (const _CharT *__lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
bool operator>= (const _Pointer_adapter< _Tp > &__lhs, const _Pointer_adapter< _Tp > &__rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator>= (const _Pointer_adapter< _Tp1 > &__lhs, _Tp2 __rhs)
template<typename _Tp1 , typename _Tp2 >
bool operator>= (const _Pointer_adapter< _Tp1 > &__lhs, const _Pointer_adapter< _Tp2 > &__rhs)
template<class _CharT , class _Alloc >
bool operator>= (const _Rope_const_iterator< _CharT, _Alloc > &__x, const _Rope_const_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator>= (const _Rope_iterator< _CharT, _Alloc > &__x, const _Rope_iterator< _CharT, _Alloc > &__y)
template<class _CharT , class _Alloc >
bool operator>= (const rope< _CharT, _Alloc > &__x, const rope< _CharT, _Alloc > &__y)
template<class _Tp , class _Alloc >
bool operator>= (const slist< _Tp, _Alloc > &_SL1, const slist< _Tp, _Alloc > &_SL2)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::beta_distribution< _RealType > &__x)
template<typename _UIntType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::hypergeometric_distribution< _UIntType > &__x)
template<size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > &__x)
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4, typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::triangular_distribution< _RealType > &__x)
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::uniform_inside_sphere_distribution< _Dimen, _RealType > &__x)
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::uniform_on_sphere_distribution< _Dimen, _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, __gnu_cxx::von_mises_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, arcsine_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, hoyt_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, k_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, logistic_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, nakagami_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, pareto_distribution< _RealType > &__x)
template<typename _RealType , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, rice_distribution< _RealType > &__x)
template<typename _Tp , typename _Integer >
_Tp power (_Tp __x, _Integer __n)
template<typename _Tp , typename _Integer , typename _MonoidOperation >
_Tp power (_Tp __x, _Integer __n, _MonoidOperation __monoid_op)
template<typename _InputIterator , typename _RandomAccessIterator >
_RandomAccessIterator random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last)
template<typename _InputIterator , typename _RandomAccessIterator , typename _RandomNumberGenerator >
_RandomAccessIterator random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out_first, _RandomAccessIterator __out_last, _RandomNumberGenerator &__rand)
template<typename _ForwardIterator , typename _OutputIterator , typename _Distance >
_OutputIterator random_sample_n (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distance __n)
template<typename _ForwardIterator , typename _OutputIterator , typename _Distance , typename _RandomNumberGenerator >
_OutputIterator random_sample_n (_ForwardIterator __first, _ForwardIterator __last, _OutputIterator __out, const _Distance __n, _RandomNumberGenerator &__rand)
void rotate (_Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __first, _Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __middle, _Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __last)
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base>
void swap (__versa_string< _CharT, _Traits, _Alloc, _Base > &__lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > &__rhs)
template<typename _Tp >
void swap (_ExtPtr_allocator< _Tp > &__larg, _ExtPtr_allocator< _Tp > &__rarg)
template<class _CharT , class __Alloc >
void swap (_Rope_char_ref_proxy< _CharT, __Alloc > __a, _Rope_char_ref_proxy< _CharT, __Alloc > __b)
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc >
void swap (hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc >
void swap (hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm1, hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > &__hm2)
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc >
void swap (hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs1, hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc >
void swap (hash_set< _Val, _HashFcn, _EqualKey, _Alloc > &__hs1, hash_set< _Val, _HashFcn, _EqualKey, _Alloc > &__hs2)
template<class _Val , class _Key , class _HF , class _Extract , class _EqKey , class _All >
void swap (hashtable< _Val, _Key, _HF, _Extract, _EqKey, _All > &__ht1, hashtable< _Val, _Key, _HF, _Extract, _EqKey, _All > &__ht2)
template<class _CharT , class _Alloc >
void swap (rope< _CharT, _Alloc > &__x, rope< _CharT, _Alloc > &__y)
template<class _Tp , class _Alloc >
void swap (slist< _Tp, _Alloc > &__x, slist< _Tp, _Alloc > &__y)
template<typename _Cond >
void swap (throw_value_base< _Cond > &__a, throw_value_base< _Cond > &__b)
template<typename _InputIter , typename _Size , typename _ForwardIter >
std::pair< _InputIter, _ForwardIter > uninitialized_copy_n (_InputIter __first, _Size __count, _ForwardIter __result)
Variables
const _Lock_policy __default_lock_policy
template<class _CharT , class _Alloc >
rope< _CharT, _Alloc > identity_element (_Rope_Concat_fn< _CharT, _Alloc >)
Detailed Description
GNU extensions for public use.
Typedef Documentation
__destroy_handler
typedef void(* __gnu_cxx::__destroy_handler) (void *)
Definition at line 48 of file mt_allocator.h.
__int_traits
template<typename _Tp > using __gnu_cxx::__int_traits = typedef __numeric_traits_integer<_Tp>
Convenience alias for __numeric_traits<integer-type>.
Definition at line 138 of file ext/numeric_traits.h.
__rc_string
typedef __versa_string<char, std::char_traits<char>, std::allocator<char>, __rc_string_base> __gnu_cxx::__rc_string
Definition at line 61 of file vstring_fwd.h.
__sso_string
typedef __vstring __gnu_cxx::__sso_string
Definition at line 58 of file vstring_fwd.h.
__u16rc_string
typedef __versa_string<char16_t, std::char_traits<char16_t>, std::allocator<char16_t>, __rc_string_base> __gnu_cxx::__u16rc_string
Definition at line 74 of file vstring_fwd.h.
__u16sso_string
typedef __u16vstring __gnu_cxx::__u16sso_string
Definition at line 71 of file vstring_fwd.h.
__u16vstring
typedef __versa_string<char16_t> __gnu_cxx::__u16vstring
Definition at line 70 of file vstring_fwd.h.
__u32rc_string
typedef __versa_string<char32_t, std::char_traits<char32_t>, std::allocator<char32_t>, __rc_string_base> __gnu_cxx::__u32rc_string
Definition at line 80 of file vstring_fwd.h.
__u32sso_string
typedef __u32vstring __gnu_cxx::__u32sso_string
Definition at line 77 of file vstring_fwd.h.
__u32vstring
typedef __versa_string<char32_t> __gnu_cxx::__u32vstring
Definition at line 76 of file vstring_fwd.h.
__vstring
typedef __versa_string<char> __gnu_cxx::__vstring
Definition at line 57 of file vstring_fwd.h.
__wrc_string
typedef __versa_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t>, __rc_string_base> __gnu_cxx::__wrc_string
Definition at line 67 of file vstring_fwd.h.
__wsso_string
typedef __wvstring __gnu_cxx::__wsso_string
Definition at line 64 of file vstring_fwd.h.
__wvstring
typedef __versa_string<wchar_t> __gnu_cxx::__wvstring
Definition at line 63 of file vstring_fwd.h.
crope
typedef rope<char> __gnu_cxx::crope
Definition at line 2955 of file rope.
wrope
typedef rope<wchar_t> __gnu_cxx::wrope
Definition at line 2956 of file rope.
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 199 of file backward/hashtable.h.
_Lock_policy
enum __gnu_cxx::_Lock_policy
Definition at line 49 of file concurrence.h.
Function Documentation
__atomic_add_dispatch()
void __gnu_cxx::__atomic_add_dispatch (_Atomic_word * __mem, int __val) inline
Definition at line 106 of file atomicity.h.
__atomic_add_single()
void __gnu_cxx::__atomic_add_single (_Atomic_word * __mem, int __val) inline
Definition at line 91 of file atomicity.h.
__aux_require_boolean_expr()
template<class _Tp > void __gnu_cxx::__aux_require_boolean_expr (const _Tp & __t)
Definition at line 254 of file boost_concept_check.h.
__const_pointer_cast() [1/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__const_pointer_cast (_FromType * __arg) inline
Definition at line 108 of file cast.h.
__const_pointer_cast() [2/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__const_pointer_cast (const _FromType & __arg) inline
Definition at line 80 of file cast.h.
__copy_n() [1/2]
template<typename _InputIterator , typename _Size , typename _OutputIterator > std::pair< _InputIterator, _OutputIterator > __gnu_cxx::__copy_n (_InputIterator __first, _Size __count, _OutputIterator __result, std::input_iterator_tag)
Definition at line 74 of file ext/algorithm.
__copy_n() [2/2]
template<typename _RAIterator , typename _Size , typename _OutputIterator > std::pair< _RAIterator, _OutputIterator > __gnu_cxx::__copy_n (_RAIterator __first, _Size __count, _OutputIterator __result, std::random_access_iterator_tag) inline
Definition at line 89 of file ext/algorithm.
__distance() [1/2]
template<typename _InputIterator , typename _Distance > void __gnu_cxx::__distance (_InputIterator __first, _InputIterator __last, _Distance & __n, std::input_iterator_tag) inline
Definition at line 75 of file ext/iterator.
__distance() [2/2]
template<typename _RandomAccessIterator , typename _Distance > void __gnu_cxx::__distance (_RandomAccessIterator __first, _RandomAccessIterator __last, _Distance & __n, std::random_access_iterator_tag) inline
Definition at line 89 of file ext/iterator.
__dynamic_pointer_cast() [1/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__dynamic_pointer_cast (_FromType * __arg) inline
Definition at line 102 of file cast.h.
__dynamic_pointer_cast() [2/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__dynamic_pointer_cast (const _FromType & __arg) inline
Definition at line 74 of file cast.h.
__exchange_and_add_dispatch()
_Atomic_word __gnu_cxx::__exchange_and_add_dispatch (_Atomic_word * __mem, int __val) inline
Definition at line 96 of file atomicity.h.
__exchange_and_add_single()
_Atomic_word __gnu_cxx::__exchange_and_add_single (_Atomic_word * __mem, int __val) inline
Definition at line 82 of file atomicity.h.
__function_requires()
template<class _Concept > constexpr void __gnu_cxx::__function_requires () inline constexpr
Definition at line 76 of file boost_concept_check.h.
__is_null_pointer() [1/3]
template<typename _Type > constexpr bool __gnu_cxx::__is_null_pointer (_Type * __ptr) inline constexpr
Definition at line 153 of file type_traits.h.
__is_null_pointer() [2/3]
template<typename _Type > constexpr bool __gnu_cxx::__is_null_pointer (_Type) inline constexpr
Definition at line 159 of file type_traits.h.
__is_null_pointer() [3/3]
constexpr bool __gnu_cxx::__is_null_pointer (std::nullptr_t) constexpr
Definition at line 164 of file type_traits.h.
__is_single_threaded()
bool __gnu_cxx::__is_single_threaded () inline noexcept
Definition at line 47 of file atomicity.h.
__lexicographical_compare_3way() [1/3]
template<typename _InputIterator1 , typename _InputIterator2 > int __gnu_cxx::__lexicographical_compare_3way (_InputIterator1 __first1, _InputIterator1 __last1, _InputIterator2 __first2, _InputIterator2 __last2)
Definition at line 128 of file ext/algorithm.
__lexicographical_compare_3way() [2/3]
int __gnu_cxx::__lexicographical_compare_3way (const char * __first1, const char * __last1, const char * __first2, const char * __last2) inline
Definition at line 163 of file ext/algorithm.
__lexicographical_compare_3way() [3/3]
int __gnu_cxx::__lexicographical_compare_3way (const unsigned char * __first1, const unsigned char * __last1, const unsigned char * __first2, const unsigned char * __last2) inline
Definition at line 149 of file ext/algorithm.
__mutable_reference_at()
crope::reference __gnu_cxx::__mutable_reference_at (crope & __c, std::size_t __i) inline
Definition at line 2959 of file rope.
__power() [1/2]
template<typename _Tp , typename _Integer > _Tp __gnu_cxx::__power (_Tp __x, _Integer __n) inline
Definition at line 103 of file ext/numeric.
__power() [2/2]
template<typename _Tp , typename _Integer , typename _MonoidOperation > _Tp __gnu_cxx::__power (_Tp __x, _Integer __n, _MonoidOperation __monoid_op)
Definition at line 76 of file ext/numeric.
__random_sample() [1/2]
template<typename _InputIterator , typename _RandomAccessIterator , typename _RandomNumberGenerator , typename _Distance > _RandomAccessIterator __gnu_cxx::__random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out, _RandomNumberGenerator & __rand, const _Distance __n)
Definition at line 351 of file ext/algorithm.
__random_sample() [2/2]
template<typename _InputIterator , typename _RandomAccessIterator , typename _Distance > _RandomAccessIterator __gnu_cxx::__random_sample (_InputIterator __first, _InputIterator __last, _RandomAccessIterator __out, const _Distance __n)
Definition at line 328 of file ext/algorithm.
__reinterpret_pointer_cast() [1/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__reinterpret_pointer_cast (_FromType * __arg) inline
Definition at line 114 of file cast.h.
__reinterpret_pointer_cast() [2/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__reinterpret_pointer_cast (const _FromType & __arg) inline
Definition at line 86 of file cast.h.
__slist_make_link()
_Slist_node_base * __gnu_cxx::__slist_make_link (_Slist_node_base * __prev_node, _Slist_node_base * __new_node) inline
Definition at line 66 of file slist.
__slist_previous() [1/2]
_Slist_node_base * __gnu_cxx::__slist_previous (_Slist_node_base * __head, const _Slist_node_base * __node) inline
Definition at line 75 of file slist.
__slist_previous() [2/2]
const _Slist_node_base * __gnu_cxx::__slist_previous (const _Slist_node_base * __head, const _Slist_node_base * __node) inline
Definition at line 84 of file slist.
__slist_reverse()
_Slist_node_base * __gnu_cxx::__slist_reverse (_Slist_node_base * __node) inline
Definition at line 121 of file slist.
__slist_size()
std::size_t __gnu_cxx::__slist_size (_Slist_node_base * __node) inline
Definition at line 137 of file slist.
__slist_splice_after() [1/2]
void __gnu_cxx::__slist_splice_after (_Slist_node_base * __pos, _Slist_node_base * __before_first, _Slist_node_base * __before_last) inline
Definition at line 93 of file slist.
__slist_splice_after() [2/2]
void __gnu_cxx::__slist_splice_after (_Slist_node_base * __pos, _Slist_node_base * __head) inline
Definition at line 108 of file slist.
__static_pointer_cast() [1/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__static_pointer_cast (_FromType * __arg) inline
Casting operations for cases where _FromType is a standard pointer. _ToType can be a standard or non-standard pointer.
Definition at line 96 of file cast.h.
__static_pointer_cast() [2/2]
template<typename _ToType , typename _FromType > _ToType __gnu_cxx::__static_pointer_cast (const _FromType & __arg) inline
Casting operations for cases where _FromType is not a standard pointer. _ToType can be a standard or non-standard pointer. Given that _FromType is not a pointer, it must have a get() method that returns the standard pointer equivalent of the address it points to, and must have an element_type typedef which names the type it points to.
Definition at line 68 of file cast.h.
__stl_hash_string()
size_t __gnu_cxx::__stl_hash_string (const char * __s) inline
Definition at line 71 of file hash_fun.h.
__stl_next_prime()
unsigned long __gnu_cxx::__stl_next_prime (unsigned long __n) inline
Definition at line 228 of file backward/hashtable.h.
__stoa()
template<typename _TRet , typename _Ret = _TRet, typename _CharT , typename... _Base> _Ret __gnu_cxx::__stoa (_TRet(*)(const _CharT *, _CharT **, _Base...) __convf, const char * __name, const _CharT * __str, std::size_t * __idx, _Base... __base)
Definition at line 56 of file string_conversions.h.
__throw_concurrence_lock_error()
void __gnu_cxx::__throw_concurrence_lock_error () inline
Definition at line 98 of file concurrence.h.
__throw_concurrence_unlock_error()
void __gnu_cxx::__throw_concurrence_unlock_error () inline
Definition at line 102 of file concurrence.h.
__throw_forced_error()
void __gnu_cxx::__throw_forced_error () inline
Definition at line 86 of file throw_allocator.h.
__to_xstring()
template<typename _String , typename _CharT = typename _String::value_type> _String __gnu_cxx::__to_xstring (int(*)(_CharT *, std::size_t, const _CharT *, __builtin_va_list) __convf, std::size_t __n, const _CharT * __fmt, ...)
Definition at line 101 of file string_conversions.h.
__uninitialized_copy_n() [1/3]
template<typename _InputIter , typename _Size , typename _ForwardIter > std::pair< _InputIter, _ForwardIter > __gnu_cxx::__uninitialized_copy_n (_InputIter __first, _Size __count, _ForwardIter __result) inline
Definition at line 104 of file ext/memory.
__uninitialized_copy_n() [2/3]
template<typename _InputIter , typename _Size , typename _ForwardIter > std::pair< _InputIter, _ForwardIter > __gnu_cxx::__uninitialized_copy_n (_InputIter __first, _Size __count, _ForwardIter __result, std::input_iterator_tag)
Definition at line 74 of file ext/memory.
__uninitialized_copy_n() [3/3]
template<typename _RandomAccessIter , typename _Size , typename _ForwardIter > std::pair< _RandomAccessIter, _ForwardIter > __gnu_cxx::__uninitialized_copy_n (_RandomAccessIter __first, _Size __count, _ForwardIter __result, std::random_access_iterator_tag) inline
Definition at line 93 of file ext/memory.
__uninitialized_copy_n_a() [1/2]
template<typename _InputIter , typename _Size , typename _ForwardIter , typename _Allocator > std::pair< _InputIter, _ForwardIter > __gnu_cxx::__uninitialized_copy_n_a (_InputIter __first, _Size __count, _ForwardIter __result, _Allocator __alloc)
Definition at line 136 of file ext/memory.
__uninitialized_copy_n_a() [2/2]
template<typename _InputIter , typename _Size , typename _ForwardIter , typename _Tp > std::pair< _InputIter, _ForwardIter > __gnu_cxx::__uninitialized_copy_n_a (_InputIter __first, _Size __count, _ForwardIter __result, std::allocator< _Tp >) inline
Definition at line 157 of file ext/memory.
_Bit_scan_forward()
std::size_t __gnu_cxx::_Bit_scan_forward (std::size_t __num) inline
Generic Version of the bsf instruction.
Definition at line 509 of file bitmap_allocator.h.
Referenced by __gnu_cxx::bitmap_allocator< _Tp >::_M_allocate_single_object().
_Destroy_const() [1/2]
template<typename _ForwardIterator , typename _Allocator > void __gnu_cxx::_Destroy_const (_ForwardIterator __first, _ForwardIterator __last, _Allocator __alloc)
Definition at line 82 of file rope.
_Destroy_const() [2/2]
template<typename _ForwardIterator , typename _Tp > void __gnu_cxx::_Destroy_const (_ForwardIterator __first, _ForwardIterator __last, std::allocator< _Tp >) inline
Definition at line 91 of file rope.
_Rope_fill()
template<class _CharT , class _Traits > void __gnu_cxx::_Rope_fill (std::basic_ostream< _CharT, _Traits > & __o, std::size_t __n) inline
Definition at line 985 of file ropeimpl.h.
_Rope_is_simple() [1/3]
template<class _CharT > bool __gnu_cxx::_Rope_is_simple (_CharT *) inline
Definition at line 997 of file ropeimpl.h.
_Rope_is_simple() [2/3]
bool __gnu_cxx::_Rope_is_simple (char *) inline
Definition at line 1001 of file ropeimpl.h.
_Rope_is_simple() [3/3]
bool __gnu_cxx::_Rope_is_simple (wchar_t *) inline
Definition at line 1005 of file ropeimpl.h.
_Rope_rotate()
template<class _Rope_iterator > void __gnu_cxx::_Rope_rotate (_Rope_iterator __first, _Rope_iterator __middle, _Rope_iterator __last)
Definition at line 1666 of file ropeimpl.h.
_S_cond_store_eos() [1/3]
template<class _CharT > void __gnu_cxx::_S_cond_store_eos (_CharT &) inline
Definition at line 133 of file rope.
_S_cond_store_eos() [2/3]
void __gnu_cxx::_S_cond_store_eos (char & __c) inline
Definition at line 136 of file rope.
_S_cond_store_eos() [3/3]
void __gnu_cxx::_S_cond_store_eos (wchar_t & __c) inline
Definition at line 140 of file rope.
_S_eos()
template<class _CharT > _CharT __gnu_cxx::_S_eos (_CharT *) inline
Definition at line 102 of file rope.
_S_is_basic_char_type() [1/3]
template<class _CharT > bool __gnu_cxx::_S_is_basic_char_type (_CharT *) inline
Definition at line 109 of file rope.
_S_is_basic_char_type() [2/3]
bool __gnu_cxx::_S_is_basic_char_type (char *) inline
Definition at line 118 of file rope.
_S_is_basic_char_type() [3/3]
bool __gnu_cxx::_S_is_basic_char_type (wchar_t *) inline
Definition at line 126 of file rope.
_S_is_one_byte_char_type() [1/2]
template<class _CharT > bool __gnu_cxx::_S_is_one_byte_char_type (_CharT *) inline
Definition at line 114 of file rope.
_S_is_one_byte_char_type() [2/2]
bool __gnu_cxx::_S_is_one_byte_char_type (char *) inline
Definition at line 122 of file rope.
count()
template<typename _InputIterator , typename _Tp , typename _Size > void __gnu_cxx::count (_InputIterator __first, _InputIterator __last, const _Tp & __value, _Size & __n)
Definition at line 219 of file ext/algorithm.
count_if()
template<typename _InputIterator , typename _Predicate , typename _Size > void __gnu_cxx::count_if (_InputIterator __first, _InputIterator __last, _Predicate __pred, _Size & __n)
Definition at line 237 of file ext/algorithm.
mem_fun1() [1/2]
template<class _Ret , class _Tp , class _Arg > std::const_mem_fun1_t< _Ret, _Tp, _Arg > __gnu_cxx::mem_fun1 (_Ret(_Tp::*)(_Arg) const __f) inline
Definition at line 410 of file ext/functional.
mem_fun1() [2/2]
template<class _Ret , class _Tp , class _Arg > std::mem_fun1_t< _Ret, _Tp, _Arg > __gnu_cxx::mem_fun1 (_Ret(_Tp::*)(_Arg) __f) inline
Definition at line 405 of file ext/functional.
mem_fun1_ref() [1/2]
template<class _Ret , class _Tp , class _Arg > std::const_mem_fun1_ref_t< _Ret, _Tp, _Arg > __gnu_cxx::mem_fun1_ref (_Ret(_Tp::*)(_Arg) const __f) inline
Definition at line 420 of file ext/functional.
mem_fun1_ref() [2/2]
template<class _Ret , class _Tp , class _Arg > std::mem_fun1_ref_t< _Ret, _Tp, _Arg > __gnu_cxx::mem_fun1_ref (_Ret(_Tp::*)(_Arg) __f) inline
Definition at line 415 of file ext/functional.
operator!=() [1/21]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator!= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 504 of file pointer.h.
operator!=() [2/21]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator!= (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1241 of file bits/stl_iterator.h.
operator!=() [3/21]
template<typename _IteratorL , typename _IteratorR , typename _Container > constexpr bool __gnu_cxx::operator!= (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline constexpr noexcept
Definition at line 1233 of file bits/stl_iterator.h.
operator!=() [4/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator!= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test difference of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 2387 of file vstring.h.
operator!=() [5/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator!= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test difference of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) != 0. False otherwise.
Definition at line 2413 of file vstring.h.
operator!=() [6/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator!= (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test difference of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) != 0. False otherwise.
Definition at line 2400 of file vstring.h.
operator!=() [7/21]
template<typename _Tp > bool __gnu_cxx::operator!= (const _Pointer_adapter< _Tp > & __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 549 of file pointer.h.
operator!=() [8/21]
template<typename _Tp > bool __gnu_cxx::operator!= (const _Pointer_adapter< _Tp > & __lhs, int __rhs) inline
Definition at line 523 of file pointer.h.
operator!=() [9/21]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator!= (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 504 of file pointer.h.
operator!=() [10/21]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator!= (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 504 of file pointer.h.
operator!=() [11/21]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator!= (const _Rope_char_ptr_proxy< _CharT, _Alloc > & __x, const _Rope_char_ptr_proxy< _CharT, _Alloc > & __y) inline
Definition at line 2946 of file rope.
operator!=() [12/21]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator!= (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2728 of file rope.
operator!=() [13/21]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator!= (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2794 of file rope.
operator!=() [14/21]
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > bool __gnu_cxx::operator!= (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm2) inline
Definition at line 276 of file hash_map.
operator!=() [15/21]
template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc > bool __gnu_cxx::operator!= (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > & __hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > & __hm2) inline
Definition at line 491 of file hash_map.
operator!=() [16/21]
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc > bool __gnu_cxx::operator!= (const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs1, const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 461 of file hash_set.
operator!=() [17/21]
template<class _Value , class _HashFcn , class _EqualKey , class _Alloc > bool __gnu_cxx::operator!= (const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > & __hs1, const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 267 of file hash_set.
operator!=() [18/21]
template<class _Val , class _Key , class _HF , class _Ex , class _Eq , class _All > bool __gnu_cxx::operator!= (const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > & __ht1, const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > & __ht2) inline
Definition at line 745 of file backward/hashtable.h.
operator!=() [19/21]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator!= (const rope< _CharT, _Alloc > & __x, const rope< _CharT, _Alloc > & __y) inline
Definition at line 2922 of file rope.
operator!=() [20/21]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator!= (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 820 of file slist.
operator!=() [21/21]
template<typename _Tp > bool __gnu_cxx::operator!= (int __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 528 of file pointer.h.
operator*()
template<typename _Cond > throw_value_base< _Cond > __gnu_cxx::operator* (const throw_value_base< _Cond > & __a, const throw_value_base< _Cond > & __b) inline
Definition at line 731 of file throw_allocator.h.
operator+() [1/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > && __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > && __rhs) inline
Definition at line 2292 of file vstring.h.
operator+() [2/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > && __lhs, _CharT __rhs) inline
Definition at line 2326 of file vstring.h.
operator+() [3/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > && __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Definition at line 2278 of file vstring.h.
operator+() [4/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (__versa_string< _CharT, _Traits, _Alloc, _Base > && __lhs, const _CharT * __rhs) inline
Definition at line 2319 of file vstring.h.
operator+() [5/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (_CharT __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > && __rhs) inline
Definition at line 2312 of file vstring.h.
operator+() [6/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (_CharT __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs)
Concatenate character and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 213 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::append(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::push_back(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::reserve(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator+() [7/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > && __rhs) inline
Definition at line 2285 of file vstring.h.
operator+() [8/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, _CharT __rhs)
Concatenate string and character.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 243 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::append(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::push_back(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::reserve(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator+() [9/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs)
Concatenate two strings.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
Definition at line 183 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::append(), __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::reserve(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator+() [10/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs)
Concatenate string and C string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with __lhs followed by __rhs.
Definition at line 226 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator+() [11/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const _CharT * __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > && __rhs) inline
Definition at line 2305 of file vstring.h.
operator+() [12/21]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> __versa_string< _CharT, _Traits, _Alloc, _Base > __gnu_cxx::operator+ (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs)
Concatenate C string and string.
Parameters
__lhs First string.
__rhs Last string.
Returns
New string with value of __lhs followed by __rhs.
Definition at line 196 of file vstring.tcc.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator+() [13/21]
template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > __gnu_cxx::operator+ (const _Rope_const_iterator< _CharT, _Alloc > & __x, std::ptrdiff_t __n) inline
Definition at line 2767 of file rope.
operator+() [14/21]
template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > __gnu_cxx::operator+ (const _Rope_iterator< _CharT, _Alloc > & __x, std::ptrdiff_t __n) inline
Definition at line 2832 of file rope.
operator+() [15/21]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > __gnu_cxx::operator+ (const rope< _CharT, _Alloc > & __left, _CharT __right) inline
Definition at line 2886 of file rope.
operator+() [16/21]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > __gnu_cxx::operator+ (const rope< _CharT, _Alloc > & __left, const _CharT * __right) inline
Definition at line 2865 of file rope.
operator+() [17/21]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > __gnu_cxx::operator+ (const rope< _CharT, _Alloc > & __left, const rope< _CharT, _Alloc > & __right) inline
Definition at line 2844 of file rope.
operator+() [18/21]
template<typename _Cond > throw_value_base< _Cond > __gnu_cxx::operator+ (const throw_value_base< _Cond > & __a, const throw_value_base< _Cond > & __b) inline
Definition at line 709 of file throw_allocator.h.
operator+() [19/21]
template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > __gnu_cxx::operator+ (std::ptrdiff_t __n, const _Rope_const_iterator< _CharT, _Alloc > & __x) inline
Definition at line 2774 of file rope.
operator+() [20/21]
template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > __gnu_cxx::operator+ (std::ptrdiff_t __n, const _Rope_iterator< _CharT, _Alloc > & __x) inline
Definition at line 2838 of file rope.
operator+() [21/21]
template<typename _Iterator , typename _Container > constexpr __normal_iterator< _Iterator, _Container > __gnu_cxx::operator+ (typename __normal_iterator< _Iterator, _Container >::difference_type __n, const __normal_iterator< _Iterator, _Container > & __i) inline constexpr noexcept
Definition at line 1342 of file bits/stl_iterator.h.
operator+=() [1/3]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & __gnu_cxx::operator+= (rope< _CharT, _Alloc > & __left, _CharT __right) inline
Definition at line 2896 of file rope.
operator+=() [2/3]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & __gnu_cxx::operator+= (rope< _CharT, _Alloc > & __left, const _CharT * __right) inline
Definition at line 2877 of file rope.
operator+=() [3/3]
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > & __gnu_cxx::operator+= (rope< _CharT, _Alloc > & __left, const rope< _CharT, _Alloc > & __right) inline
Definition at line 2856 of file rope.
operator-() [1/7]
template<typename _Iterator , typename _Container > constexpr __normal_iterator< _Iterator, _Container >::difference_type __gnu_cxx::operator- (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1334 of file bits/stl_iterator.h.
operator-() [2/7]
template<typename _IteratorL , typename _IteratorR , typename _Container > constexpr auto __gnu_cxx::operator- (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) -> decltype(__lhs.base() - __rhs.base()) inline constexpr noexcept
Definition at line 1321 of file bits/stl_iterator.h.
operator-() [3/7]
template<class _CharT , class _Alloc > std::ptrdiff_t __gnu_cxx::operator- (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2751 of file rope.
operator-() [4/7]
template<class _CharT , class _Alloc > _Rope_const_iterator< _CharT, _Alloc > __gnu_cxx::operator- (const _Rope_const_iterator< _CharT, _Alloc > & __x, std::ptrdiff_t __n) inline
Definition at line 2760 of file rope.
operator-() [5/7]
template<class _CharT , class _Alloc > std::ptrdiff_t __gnu_cxx::operator- (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2818 of file rope.
operator-() [6/7]
template<class _CharT , class _Alloc > _Rope_iterator< _CharT, _Alloc > __gnu_cxx::operator- (const _Rope_iterator< _CharT, _Alloc > & __x, std::ptrdiff_t __n) inline
Definition at line 2825 of file rope.
operator-() [7/7]
template<typename _Cond > throw_value_base< _Cond > __gnu_cxx::operator- (const throw_value_base< _Cond > & __a, const throw_value_base< _Cond > & __b) inline
Definition at line 720 of file throw_allocator.h.
operator<() [1/14]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator< (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 505 of file pointer.h.
operator<() [2/14]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator< (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1257 of file bits/stl_iterator.h.
operator<() [3/14]
template<typename _IteratorL , typename _IteratorR , typename _Container > bool __gnu_cxx::operator< (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline noexcept
Definition at line 1249 of file bits/stl_iterator.h.
operator<() [4/14]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator< (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if string precedes string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 2426 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<() [5/14]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator< (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test if string precedes C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 2439 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<() [6/14]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator< (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if C string precedes string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs precedes __rhs. False otherwise.
Definition at line 2452 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<() [7/14]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator< (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 505 of file pointer.h.
operator<() [8/14]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator< (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 505 of file pointer.h.
operator<() [9/14]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator< (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2723 of file rope.
operator<() [10/14]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator< (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2787 of file rope.
operator<() [11/14]
template<typename _Value , typename _Int , typename _St > bool __gnu_cxx::operator< (const character< _Value, _Int, _St > & lhs, const character< _Value, _Int, _St > & rhs) inline
Definition at line 85 of file pod_char_traits.h.
operator<() [12/14]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator< (const rope< _CharT, _Alloc > & __left, const rope< _CharT, _Alloc > & __right)
Definition at line 2903 of file rope.
operator<() [13/14]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator< (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 813 of file slist.
operator<() [14/14]
template<typename _Cond > bool __gnu_cxx::operator< (const throw_value_base< _Cond > & __a, const throw_value_base< _Cond > & __b) inline
Definition at line 696 of file throw_allocator.h.
operator<<() [1/18]
template<class _CharT , class _Traits , class _Alloc > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __o, const rope< _CharT, _Alloc > & __r)
Definition at line 1005 of file ropeimpl.h.
operator<<() [2/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::beta_distribution< _RealType > & __x)
Definition at line 441 of file ext/random.tcc.
operator<<() [3/18]
template<typename _UIntType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::hypergeometric_distribution< _UIntType > & __x)
Definition at line 1415 of file ext/random.tcc.
operator<<() [4/18]
template<size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > & __x)
Definition at line 655 of file ext/random.tcc.
operator<<() [5/18]
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4, typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > & __x)
Definition at line 325 of file ext/random.tcc.
operator<<() [6/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::triangular_distribution< _RealType > & __x)
Definition at line 1206 of file ext/random.tcc.
operator<<() [7/18]
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::uniform_inside_sphere_distribution< _Dimen, _RealType > & __x)
Definition at line 1789 of file ext/random.tcc.
operator<<() [8/18]
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::uniform_on_sphere_distribution< _Dimen, _RealType > & __x)
Definition at line 1658 of file ext/random.tcc.
operator<<() [9/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const __gnu_cxx::von_mises_distribution< _RealType > & __x)
Definition at line 1308 of file ext/random.tcc.
operator<<() [10/18]
template<typename _CharT , typename _Traits , typename _StoreT > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const _Pointer_adapter< _StoreT > & __p) inline
Definition at line 561 of file pointer.h.
operator<<() [11/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const arcsine_distribution< _RealType > & __x)
Definition at line 1032 of file ext/random.tcc.
operator<<() [12/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const hoyt_distribution< _RealType > & __x)
Definition at line 1130 of file ext/random.tcc.
operator<<() [13/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const k_distribution< _RealType > & __x)
Definition at line 960 of file ext/random.tcc.
operator<<() [14/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const logistic_distribution< _RealType > & __x)
Definition at line 1494 of file ext/random.tcc.
operator<<() [15/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const nakagami_distribution< _RealType > & __x)
Definition at line 804 of file ext/random.tcc.
operator<<() [16/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const pareto_distribution< _RealType > & __x)
Definition at line 869 of file ext/random.tcc.
operator<<() [17/18]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & __gnu_cxx::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const rice_distribution< _RealType > & __x)
Definition at line 729 of file ext/random.tcc.
operator<<() [18/18]
std::ostream & __gnu_cxx::operator<< (std::ostream & os, const annotate_base & __b) inline
Definition at line 387 of file throw_allocator.h.
operator<=() [1/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator<= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 506 of file pointer.h.
operator<=() [2/13]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator<= (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1289 of file bits/stl_iterator.h.
operator<=() [3/13]
template<typename _IteratorL , typename _IteratorR , typename _Container > bool __gnu_cxx::operator<= (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline noexcept
Definition at line 1281 of file bits/stl_iterator.h.
operator<=() [4/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator<= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if string doesn't follow string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2506 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<=() [5/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator<= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test if string doesn't follow C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2519 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<=() [6/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator<= (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if C string doesn't follow string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't follow __rhs. False otherwise.
Definition at line 2532 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator<=() [7/13]
template<typename _Tp > bool __gnu_cxx::operator<= (const _Pointer_adapter< _Tp > & __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 542 of file pointer.h.
operator<=() [8/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator<= (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 506 of file pointer.h.
operator<=() [9/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator<= (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 506 of file pointer.h.
operator<=() [10/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator<= (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2738 of file rope.
operator<=() [11/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator<= (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2805 of file rope.
operator<=() [12/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator<= (const rope< _CharT, _Alloc > & __x, const rope< _CharT, _Alloc > & __y) inline
Definition at line 2933 of file rope.
operator<=() [13/13]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator<= (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 829 of file slist.
operator==() [1/29]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator== (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 503 of file pointer.h.
operator==() [2/29]
template<size_t _Dimen, typename _RealType > bool __gnu_cxx::operator== (const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > & __d1, const __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > & __d2)
Definition at line 655 of file ext/random.tcc.
operator==() [3/29]
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4> bool __gnu_cxx::operator== (const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > & __lhs, const __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > & __rhs)
Definition at line 325 of file ext/random.tcc.
operator==() [4/29]
template<typename _Tp , typename _Poolp > bool __gnu_cxx::operator== (const __mt_alloc< _Tp, _Poolp > & , const __mt_alloc< _Tp, _Poolp > &) inline
Definition at line 773 of file mt_allocator.h.
operator==() [5/29]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator== (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1225 of file bits/stl_iterator.h.
operator==() [6/29]
template<typename _IteratorL , typename _IteratorR , typename _Container > constexpr bool __gnu_cxx::operator== (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline constexpr noexcept
Definition at line 1217 of file bits/stl_iterator.h.
operator==() [7/29]
template<typename _Tp > bool __gnu_cxx::operator== (const __pool_alloc< _Tp > & , const __pool_alloc< _Tp > &) inline
Definition at line 200 of file pool_allocator.h.
operator==() [8/29]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator== (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test equivalence of two strings.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 2341 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::data(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator==() [9/29]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator== (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test equivalence of string and C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs.compare(__rhs) == 0. False otherwise.
Definition at line 2357 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::data(), and __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::size().
operator==() [10/29]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator== (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test equivalence of C string and string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __rhs.compare(__lhs) == 0. False otherwise.
Definition at line 2373 of file vstring.h.
operator==() [11/29]
template<typename _Tp > bool __gnu_cxx::operator== (const _Pointer_adapter< _Tp > & __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Comparison operators for _Pointer_adapter defer to the base class' comparison operators, when possible.
Definition at line 537 of file pointer.h.
operator==() [12/29]
template<typename _Tp > bool __gnu_cxx::operator== (const _Pointer_adapter< _Tp > & __lhs, int __rhs) inline
Definition at line 513 of file pointer.h.
operator==() [13/29]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator== (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 503 of file pointer.h.
operator==() [14/29]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator== (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 503 of file pointer.h.
operator==() [15/29]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator== (const _Rope_char_ptr_proxy< _CharT, _Alloc > & __x, const _Rope_char_ptr_proxy< _CharT, _Alloc > & __y) inline
Definition at line 2916 of file rope.
operator==() [16/29]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator== (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2717 of file rope.
operator==() [17/29]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator== (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2781 of file rope.
operator==() [18/29]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator== (const bitmap_allocator< _Tp1 > & , const bitmap_allocator< _Tp2 > &) throw ()
Definition at line 1098 of file bitmap_allocator.h.
operator==() [19/29]
template<typename _Value , typename _Int , typename _St > bool __gnu_cxx::operator== (const character< _Value, _Int, _St > & lhs, const character< _Value, _Int, _St > & rhs) inline
Definition at line 80 of file pod_char_traits.h.
operator==() [20/29]
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > bool __gnu_cxx::operator== (const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm1, const hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm2) inline
Definition at line 270 of file hash_map.
operator==() [21/29]
template<class _Key , class _Tp , class _HF , class _EqKey , class _Alloc > bool __gnu_cxx::operator== (const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > & __hm1, const hash_multimap< _Key, _Tp, _HF, _EqKey, _Alloc > & __hm2) inline
Definition at line 485 of file hash_map.
operator==() [22/29]
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc > bool __gnu_cxx::operator== (const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs1, const hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 455 of file hash_set.
operator==() [23/29]
template<class _Value , class _HashFcn , class _EqualKey , class _Alloc > bool __gnu_cxx::operator== (const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > & __hs1, const hash_set< _Value, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 261 of file hash_set.
operator==() [24/29]
template<class _Val , class _Key , class _HF , class _Ex , class _Eq , class _All > bool __gnu_cxx::operator== (const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > & __ht1, const hashtable< _Val, _Key, _HF, _Ex, _Eq, _All > & __ht2)
Definition at line 704 of file backward/hashtable.h.
operator==() [25/29]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator== (const rope< _CharT, _Alloc > & __left, const rope< _CharT, _Alloc > & __right)
Definition at line 2910 of file rope.
operator==() [26/29]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator== (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 795 of file slist.
operator==() [27/29]
template<typename _Tp , typename _Cond > bool __gnu_cxx::operator== (const throw_allocator_base< _Tp, _Cond > & , const throw_allocator_base< _Tp, _Cond > &) inline
Definition at line 912 of file throw_allocator.h.
operator==() [28/29]
template<typename _Cond > bool __gnu_cxx::operator== (const throw_value_base< _Cond > & __a, const throw_value_base< _Cond > & __b) inline
Definition at line 686 of file throw_allocator.h.
operator==() [29/29]
template<typename _Tp > bool __gnu_cxx::operator== (int __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 518 of file pointer.h.
operator>() [1/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator> (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 507 of file pointer.h.
operator>() [2/13]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator> (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1274 of file bits/stl_iterator.h.
operator>() [3/13]
template<typename _IteratorL , typename _IteratorR , typename _Container > bool __gnu_cxx::operator> (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline noexcept
Definition at line 1266 of file bits/stl_iterator.h.
operator>() [4/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator> (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if string follows string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 2467 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>() [5/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator> (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test if string follows C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 2480 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>() [6/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator> (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if C string follows string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs follows __rhs. False otherwise.
Definition at line 2493 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>() [7/13]
template<typename _Tp > bool __gnu_cxx::operator> (const _Pointer_adapter< _Tp > & __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 555 of file pointer.h.
operator>() [8/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator> (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 507 of file pointer.h.
operator>() [9/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator> (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 507 of file pointer.h.
operator>() [10/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator> (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2733 of file rope.
operator>() [11/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator> (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2800 of file rope.
operator>() [12/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator> (const rope< _CharT, _Alloc > & __x, const rope< _CharT, _Alloc > & __y) inline
Definition at line 2928 of file rope.
operator>() [13/13]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator> (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 825 of file slist.
operator>=() [1/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator>= (_Tp1 __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 508 of file pointer.h.
operator>=() [2/13]
template<typename _Iterator , typename _Container > constexpr bool __gnu_cxx::operator>= (const __normal_iterator< _Iterator, _Container > & __lhs, const __normal_iterator< _Iterator, _Container > & __rhs) inline constexpr noexcept
Definition at line 1306 of file bits/stl_iterator.h.
operator>=() [3/13]
template<typename _IteratorL , typename _IteratorR , typename _Container > bool __gnu_cxx::operator>= (const __normal_iterator< _IteratorL, _Container > & __lhs, const __normal_iterator< _IteratorR, _Container > & __rhs) inline noexcept
Definition at line 1298 of file bits/stl_iterator.h.
operator>=() [4/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator>= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if string doesn't precede string.
Parameters
__lhs First string.
__rhs Second string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2547 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>=() [5/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator>= (const __versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, const _CharT * __rhs) inline
Test if string doesn't precede C string.
Parameters
__lhs String.
__rhs C string.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2560 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>=() [6/13]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> bool __gnu_cxx::operator>= (const _CharT * __lhs, const __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Test if C string doesn't precede string.
Parameters
__lhs C string.
__rhs String.
Returns
True if __lhs doesn't precede __rhs. False otherwise.
Definition at line 2573 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::compare().
operator>=() [7/13]
template<typename _Tp > bool __gnu_cxx::operator>= (const _Pointer_adapter< _Tp > & __lhs, const _Pointer_adapter< _Tp > & __rhs) inline
Definition at line 561 of file pointer.h.
operator>=() [8/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator>= (const _Pointer_adapter< _Tp1 > & __lhs, _Tp2 __rhs) inline
Definition at line 508 of file pointer.h.
operator>=() [9/13]
template<typename _Tp1 , typename _Tp2 > bool __gnu_cxx::operator>= (const _Pointer_adapter< _Tp1 > & __lhs, const _Pointer_adapter< _Tp2 > & __rhs) inline
Definition at line 508 of file pointer.h.
operator>=() [10/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator>= (const _Rope_const_iterator< _CharT, _Alloc > & __x, const _Rope_const_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2745 of file rope.
operator>=() [11/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator>= (const _Rope_iterator< _CharT, _Alloc > & __x, const _Rope_iterator< _CharT, _Alloc > & __y) inline
Definition at line 2812 of file rope.
operator>=() [12/13]
template<class _CharT , class _Alloc > bool __gnu_cxx::operator>= (const rope< _CharT, _Alloc > & __x, const rope< _CharT, _Alloc > & __y) inline
Definition at line 2940 of file rope.
operator>=() [13/13]
template<class _Tp , class _Alloc > bool __gnu_cxx::operator>= (const slist< _Tp, _Alloc > & _SL1, const slist< _Tp, _Alloc > & _SL2) inline
Definition at line 835 of file slist.
operator>>() [1/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::beta_distribution< _RealType > & __x)
Definition at line 492 of file ext/random.tcc.
operator>>() [2/15]
template<typename _UIntType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::hypergeometric_distribution< _UIntType > & __x)
Definition at line 1454 of file ext/random.tcc.
operator>>() [3/15]
template<size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::normal_mv_distribution< _Dimen, _RealType > & __x)
Definition at line 696 of file ext/random.tcc.
operator>>() [4/15]
template<typename _UIntType , size_t __m, size_t __pos1, size_t __sl1, size_t __sl2, size_t __sr1, size_t __sr2, uint32_t __msk1, uint32_t __msk2, uint32_t __msk3, uint32_t __msk4, uint32_t __parity1, uint32_t __parity2, uint32_t __parity3, uint32_t __parity4, typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::simd_fast_mersenne_twister_engine< _UIntType, __m, __pos1, __sl1, __sl2, __sr1, __sr2, __msk1, __msk2, __msk3, __msk4, __parity1, __parity2, __parity3, __parity4 > & __x)
Definition at line 388 of file ext/random.tcc.
operator>>() [5/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::triangular_distribution< _RealType > & __x)
Definition at line 1244 of file ext/random.tcc.
operator>>() [6/15]
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::uniform_inside_sphere_distribution< _Dimen, _RealType > & __x)
Definition at line 1831 of file ext/random.tcc.
operator>>() [7/15]
template<std::size_t _Dimen, typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::uniform_on_sphere_distribution< _Dimen, _RealType > & __x)
Definition at line 1683 of file ext/random.tcc.
operator>>() [8/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, __gnu_cxx::von_mises_distribution< _RealType > & __x)
Definition at line 1346 of file ext/random.tcc.
operator>>() [9/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, arcsine_distribution< _RealType > & __x)
Definition at line 1076 of file ext/random.tcc.
operator>>() [10/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, hoyt_distribution< _RealType > & __x)
Definition at line 1181 of file ext/random.tcc.
operator>>() [11/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, k_distribution< _RealType > & __x)
Definition at line 1007 of file ext/random.tcc.
operator>>() [12/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, logistic_distribution< _RealType > & __x)
Definition at line 1541 of file ext/random.tcc.
operator>>() [13/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, nakagami_distribution< _RealType > & __x)
Definition at line 845 of file ext/random.tcc.
operator>>() [14/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, pareto_distribution< _RealType > & __x)
Definition at line 910 of file ext/random.tcc.
operator>>() [15/15]
template<typename _RealType , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & __gnu_cxx::operator>> (std::basic_istream< _CharT, _Traits > & __is, rice_distribution< _RealType > & __x)
Definition at line 779 of file ext/random.tcc.
rotate()
void __gnu_cxx::rotate (_Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __first, _Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __middle, _Rope_iterator< char, __STL_DEFAULT_ALLOCATOR(char)> __last) inline
Definition at line 1690 of file ropeimpl.h.
swap() [1/11]
template<typename _CharT , typename _Traits , typename _Alloc , template< typename, typename, typename > class _Base> void __gnu_cxx::swap (__versa_string< _CharT, _Traits, _Alloc, _Base > & __lhs, __versa_string< _CharT, _Traits, _Alloc, _Base > & __rhs) inline
Swap contents of two strings.
Parameters
__lhs First string.
__rhs Second string.
Exchanges the contents of __lhs and __rhs in constant time.
Definition at line 2587 of file vstring.h.
References __gnu_cxx::__versa_string< _CharT, _Traits, _Alloc, _Base >::swap().
swap() [2/11]
template<typename _Tp > void __gnu_cxx::swap (_ExtPtr_allocator< _Tp > & __larg, _ExtPtr_allocator< _Tp > & __rarg) inline
Definition at line 196 of file extptr_allocator.h.
swap() [3/11]
template<class _CharT , class __Alloc > void __gnu_cxx::swap (_Rope_char_ref_proxy< _CharT, __Alloc > __a, _Rope_char_ref_proxy< _CharT, __Alloc > __b) inline
Definition at line 1020 of file rope.
swap() [4/11]
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > void __gnu_cxx::swap (hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm1, hash_map< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm2) inline
Definition at line 282 of file hash_map.
swap() [5/11]
template<class _Key , class _Tp , class _HashFn , class _EqlKey , class _Alloc > void __gnu_cxx::swap (hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm1, hash_multimap< _Key, _Tp, _HashFn, _EqlKey, _Alloc > & __hm2) inline
Definition at line 497 of file hash_map.
swap() [6/11]
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc > void __gnu_cxx::swap (hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs1, hash_multiset< _Val, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 467 of file hash_set.
swap() [7/11]
template<class _Val , class _HashFcn , class _EqualKey , class _Alloc > void __gnu_cxx::swap (hash_set< _Val, _HashFcn, _EqualKey, _Alloc > & __hs1, hash_set< _Val, _HashFcn, _EqualKey, _Alloc > & __hs2) inline
Definition at line 273 of file hash_set.
swap() [8/11]
template<class _Val , class _Key , class _HF , class _Extract , class _EqKey , class _All > void __gnu_cxx::swap (hashtable< _Val, _Key, _HF, _Extract, _EqKey, _All > & __ht1, hashtable< _Val, _Key, _HF, _Extract, _EqKey, _All > & __ht2) inline
Definition at line 752 of file backward/hashtable.h.
swap() [9/11]
template<class _CharT , class _Alloc > void __gnu_cxx::swap (rope< _CharT, _Alloc > & __x, rope< _CharT, _Alloc > & __y) inline
Definition at line 2968 of file rope.
swap() [10/11]
template<class _Tp , class _Alloc > void __gnu_cxx::swap (slist< _Tp, _Alloc > & __x, slist< _Tp, _Alloc > & __y) inline
Definition at line 840 of file slist.
swap() [11/11]
template<typename _Cond > void __gnu_cxx::swap (throw_value_base< _Cond > & __a, throw_value_base< _Cond > & __b) inline
Definition at line 674 of file throw_allocator.h.
Variable Documentation
__default_lock_policy
const _Lock_policy __gnu_cxx::__default_lock_policy inline
Definition at line 53 of file concurrence.h.
identity_element
template<class _CharT , class _Alloc > rope< _CharT, _Alloc > __gnu_cxx::identity_element(_Rope_Concat_fn< _CharT, _Alloc >) (_Rope_Concat_fn< _CharT, _Alloc >) inline
Definition at line 460 of file rope.