libstdc++: std::basic_string< _CharT, _Traits, _Alloc > Class Template Reference
std::basic_string< _CharT, _Traits, _Alloc > Class Template Reference
Strings | Containers » Sequences
#include <string>
Public Types
typedef _Alloc allocator_type
typedef __gnu_cxx::__normal_iterator< const_pointer, basic_string > const_iterator
typedef _CharT_alloc_traits::const_pointer const_pointer
typedef const value_type & const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef _CharT_alloc_traits::difference_type difference_type
typedef __gnu_cxx::__normal_iterator< pointer, basic_string > iterator
typedef _CharT_alloc_traits::pointer pointer
typedef value_type & reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef _CharT_alloc_traits::size_type size_type
typedef _Traits traits_type
typedef _Traits::char_type value_type
Public Member Functions
basic_string () noexcept
template<class _InputIterator >
basic_string (_InputIterator __beg, _InputIterator __end, const _Alloc &__a=_Alloc())
basic_string (basic_string &&__str) noexcept
basic_string (basic_string &&__str, const _Alloc &__a)
basic_string (const _Alloc &__a)
template<typename = _RequireAllocator<_Alloc>>
basic_string (const _CharT *__s, const _Alloc &__a=_Alloc())
basic_string (const _CharT *__s, size_type __n, const _Alloc &__a=_Alloc())
template<typename _Tp , typename = _If_sv<_Tp, void>>
basic_string (const _Tp &__t, const _Alloc &__a=_Alloc())
template<typename _Tp , typename = enable_if_t<is_convertible_v<const _Tp&, __sv_type>>>
basic_string (const _Tp &__t, size_type __pos, size_type __n, const _Alloc &__a=_Alloc())
basic_string (const basic_string &__str)
basic_string (const basic_string &__str, const _Alloc &__a)
basic_string (const basic_string &__str, size_type __pos, const _Alloc &__a=_Alloc())
basic_string (const basic_string &__str, size_type __pos, size_type __n)
basic_string (const basic_string &__str, size_type __pos, size_type __n, const _Alloc &__a)
basic_string (initializer_list< _CharT > __l, const _Alloc &__a=_Alloc())
basic_string (size_type __n, _CharT __c, const _Alloc &__a=_Alloc())
~basic_string () noexcept
template<typename _InputIterator >
basic_string< _CharT, _Traits, _Alloc > & _M_replace_dispatch (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2, __false_type)
template<typename _InIterator >
_CharT * _S_construct (_InIterator __beg, _InIterator __end, const _Alloc &__a, forward_iterator_tag)
template<class _InputIterator >
basic_string & append (_InputIterator __first, _InputIterator __last)
basic_string & append (const _CharT *__s)
basic_string & append (const _CharT *__s, size_type __n)
template<typename _Tp >
_If_sv< _Tp, basic_string & > append (const _Tp &__svt)
template<typename _Tp >
_If_sv< _Tp, basic_string & > append (const _Tp &__svt, size_type __pos, size_type __n=npos)
basic_string & append (const basic_string &__str)
basic_string & append (const basic_string &__str, size_type __pos, size_type __n=npos)
basic_string & append (initializer_list< _CharT > __l)
basic_string & append (size_type __n, _CharT __c)
template<class _InputIterator >
basic_string & assign (_InputIterator __first, _InputIterator __last)
basic_string & assign (basic_string &&__str) noexcept(allocator_traits< _Alloc >::is_always_equal::value)
basic_string & assign (const _CharT *__s)
basic_string & assign (const _CharT *__s, size_type __n)
template<typename _Tp >
_If_sv< _Tp, basic_string & > assign (const _Tp &__svt)
template<typename _Tp >
_If_sv< _Tp, basic_string & > assign (const _Tp &__svt, size_type __pos, size_type __n=npos)
basic_string & assign (const basic_string &__str)
basic_string & assign (const basic_string &__str, size_type __pos, size_type __n=npos)
basic_string & assign (initializer_list< _CharT > __l)
basic_string & assign (size_type __n, _CharT __c)
reference at (size_type __n)
const_reference at (size_type __n) const
reference back ()
const_reference back () const noexcept
iterator begin ()
const_iterator begin () const noexcept
const _CharT * c_str () const noexcept
size_type capacity () const noexcept
const_iterator cbegin () const noexcept
const_iterator cend () const noexcept
void clear () noexcept
int compare (const _CharT *__s) const noexcept
template<typename _Tp >
_If_sv< _Tp, int > compare (const _Tp &__svt) const noexcept(is_same< _Tp, __sv_type >::value)
int compare (const basic_string &__str) const
template<typename _Tp >
_If_sv< _Tp, int > compare (size_type __pos, size_type __n, const _Tp &__svt) const noexcept(is_same< _Tp, __sv_type >::value)
int compare (size_type __pos, size_type __n, const basic_string &__str) const
int compare (size_type __pos, size_type __n1, const _CharT *__s) const
int compare (size_type __pos, size_type __n1, const _CharT *__s, size_type __n2) const
template<typename _Tp >
_If_sv< _Tp, int > compare (size_type __pos1, size_type __n1, const _Tp &__svt, size_type __pos2, size_type __n2=npos) const noexcept(is_same< _Tp, __sv_type >::value)
int compare (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2=npos) const
size_type copy (_CharT *__s, size_type __n, size_type __pos=0) const
const_reverse_iterator crbegin () const noexcept
const_reverse_iterator crend () const noexcept
const _CharT * data () const noexcept
_CharT * data () noexcept
bool empty () const noexcept
iterator end ()
const_iterator end () const noexcept
bool ends_with (_CharT __x) const noexcept
bool ends_with (basic_string_view< _CharT, _Traits > __x) const noexcept
bool ends_with (const _CharT *__x) const noexcept
iterator erase (iterator __first, iterator __last)
iterator erase (iterator __position)
basic_string & erase (size_type __pos=0, size_type __n=npos)
size_type find (_CharT __c, size_type __pos=0) const noexcept
size_type find (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type find (const _CharT *__s, size_type __pos=0) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > find (const _Tp &__svt, size_type __pos=0) const noexcept(is_same< _Tp, __sv_type >::value)
size_type find (const basic_string &__str, size_type __pos=0) const noexcept
size_type find_first_not_of (_CharT __c, size_type __pos=0) const noexcept
size_type find_first_not_of (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type find_first_not_of (const _CharT *__s, size_type __pos=0) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > find_first_not_of (const _Tp &__svt, size_type __pos=0) const noexcept(is_same< _Tp, __sv_type >::value)
size_type find_first_not_of (const basic_string &__str, size_type __pos=0) const noexcept
size_type find_first_of (_CharT __c, size_type __pos=0) const noexcept
size_type find_first_of (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type find_first_of (const _CharT *__s, size_type __pos=0) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > find_first_of (const _Tp &__svt, size_type __pos=0) const noexcept(is_same< _Tp, __sv_type >::value)
size_type find_first_of (const basic_string &__str, size_type __pos=0) const noexcept
size_type find_last_not_of (_CharT __c, size_type __pos=npos) const noexcept
size_type find_last_not_of (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type find_last_not_of (const _CharT *__s, size_type __pos=npos) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > find_last_not_of (const _Tp &__svt, size_type __pos=npos) const noexcept(is_same< _Tp, __sv_type >::value)
size_type find_last_not_of (const basic_string &__str, size_type __pos=npos) const noexcept
size_type find_last_of (_CharT __c, size_type __pos=npos) const noexcept
size_type find_last_of (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type find_last_of (const _CharT *__s, size_type __pos=npos) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > find_last_of (const _Tp &__svt, size_type __pos=npos) const noexcept(is_same< _Tp, __sv_type >::value)
size_type find_last_of (const basic_string &__str, size_type __pos=npos) const noexcept
reference front ()
const_reference front () const noexcept
allocator_type get_allocator () const noexcept
iterator insert (iterator __p, _CharT __c)
template<class _InputIterator >
void insert (iterator __p, _InputIterator __beg, _InputIterator __end)
void insert (iterator __p, initializer_list< _CharT > __l)
void insert (iterator __p, size_type __n, _CharT __c)
basic_string & insert (size_type __pos, const _CharT *__s)
basic_string & insert (size_type __pos, const _CharT *__s, size_type __n)
template<typename _Tp >
_If_sv< _Tp, basic_string & > insert (size_type __pos, const _Tp &__svt)
basic_string & insert (size_type __pos, size_type __n, _CharT __c)
template<typename _Tp >
_If_sv< _Tp, basic_string & > insert (size_type __pos1, const _Tp &__svt, size_type __pos2, size_type __n=npos)
basic_string & insert (size_type __pos1, const basic_string &__str)
basic_string & insert (size_type __pos1, const basic_string &__str, size_type __pos2, size_type __n=npos)
size_type length () const noexcept
size_type max_size () const noexcept
operator __sv_type () const noexcept
basic_string & operator+= (_CharT __c)
basic_string & operator+= (const _CharT *__s)
template<typename _Tp >
_If_sv< _Tp, basic_string & > operator+= (const _Tp &__svt)
basic_string & operator+= (const basic_string &__str)
basic_string & operator+= (initializer_list< _CharT > __l)
basic_string & operator= (_CharT __c)
basic_string & operator= (basic_string &&__str) noexcept(/*conditional */)
basic_string & operator= (const _CharT *__s)
template<typename _Tp >
_If_sv< _Tp, basic_string & > operator= (const _Tp &__svt)
basic_string & operator= (const basic_string &__str)
basic_string & operator= (initializer_list< _CharT > __l)
reference operator[] (size_type __pos)
const_reference operator[] (size_type __pos) const noexcept
void pop_back ()
void push_back (_CharT __c)
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const noexcept
reverse_iterator rend ()
const_reverse_iterator rend () const noexcept
template<typename _Tp >
_If_sv< _Tp, basic_string & > replace (const_iterator __i1, const_iterator __i2, const _Tp &__svt)
basic_string & replace (iterator __i1, iterator __i2, _CharT *__k1, _CharT *__k2)
template<class _InputIterator >
basic_string & replace (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__k1, const _CharT *__k2)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s)
basic_string & replace (iterator __i1, iterator __i2, const _CharT *__s, size_type __n)
basic_string & replace (iterator __i1, iterator __i2, const basic_string &__str)
basic_string & replace (iterator __i1, iterator __i2, const_iterator __k1, const_iterator __k2)
basic_string & replace (iterator __i1, iterator __i2, initializer_list< _CharT > __l)
basic_string & replace (iterator __i1, iterator __i2, iterator __k1, iterator __k2)
basic_string & replace (iterator __i1, iterator __i2, size_type __n, _CharT __c)
template<typename _Tp >
_If_sv< _Tp, basic_string & > replace (size_type __pos, size_type __n, const _Tp &__svt)
basic_string & replace (size_type __pos, size_type __n, const basic_string &__str)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s)
basic_string & replace (size_type __pos, size_type __n1, const _CharT *__s, size_type __n2)
basic_string & replace (size_type __pos, size_type __n1, size_type __n2, _CharT __c)
template<typename _Tp >
_If_sv< _Tp, basic_string & > replace (size_type __pos1, size_type __n1, const _Tp &__svt, size_type __pos2, size_type __n2=npos)
basic_string & replace (size_type __pos1, size_type __n1, const basic_string &__str, size_type __pos2, size_type __n2=npos)
void reserve ()
void reserve (size_type __res_arg)
void resize (size_type __n)
void resize (size_type __n, _CharT __c)
size_type rfind (_CharT __c, size_type __pos=npos) const noexcept
size_type rfind (const _CharT *__s, size_type __pos, size_type __n) const noexcept
size_type rfind (const _CharT *__s, size_type __pos=npos) const noexcept
template<typename _Tp >
_If_sv< _Tp, size_type > rfind (const _Tp &__svt, size_type __pos=npos) const noexcept(is_same< _Tp, __sv_type >::value)
size_type rfind (const basic_string &__str, size_type __pos=npos) const noexcept
void shrink_to_fit () noexcept
size_type size () const noexcept
bool starts_with (_CharT __x) const noexcept
bool starts_with (basic_string_view< _CharT, _Traits > __x) const noexcept
bool starts_with (const _CharT *__x) const noexcept
basic_string substr (size_type __pos=0, size_type __n=npos) const
void swap (basic_string &__s) noexcept(/*conditional */)
Static Public Attributes
static const size_type npos
Protected Types
typedef iterator __const_iterator
Detailed Description
template<typename _CharT, typename _Traits, typename _Alloc>
class std::basic_string< _CharT, _Traits, _Alloc >
Managing sequences of characters and character-like objects.
Since
C++98
Template Parameters
_CharT Type of character
_Traits Traits for character type, defaults to char_traits<_CharT>.
_Alloc Allocator type, defaults to allocator<_CharT>.
Meets the requirements of a container, a reversible container, and a sequence. Of the optional sequence requirements, only push_back, at, and array access are supported.
Todo:
Needs documentation! See http://gcc.gnu.org/onlinedocs/libstdc++/manual/documentation_style.html
Documentation? What's that? Nathan Myers ncm@c.nosp@m.antr.nosp@m.ip.or.nosp@m.g.
A string looks like this:
                                     [_Rep]
                                     _M_length
[basic_string<char_type>]            _M_capacity
_M_dataplus                          _M_refcount
_M_p ---------------->               unnamed array of char_type
Where the _M_p points to the first character in the string, and you cast it to a pointer-to-_Rep and subtract 1 to get a pointer to the header.
This approach has the enormous advantage that a string object requires only one allocation. All the ugliness is confined within a single pair of inline functions, which each compile to a single add instruction: _Rep::_M_data(), and string::_M_rep(); and the allocation function which gets a block of raw bytes and with room enough and constructs a _Rep object at the front.
The reason you want _M_data pointing to the character array and not the _Rep is so that the debugger can see the string contents. (Probably we should add a non-inline member to get the _Rep for the debugger to use, so users can check the actual string length.)
Note that the _Rep object is a POD so that you can have a static empty string _Rep object already constructed before static constructors have run. The reference-count encoding is chosen so that a 0 indicates one reference, so you never try to destroy the empty-string _Rep object.
All but the last paragraph is considered pretty conventional for a Copy-On-Write C++ string implementation.
Definition at line 116 of file cow_string.h.
Member Typedef Documentation
__const_iterator
template<typename _CharT , typename _Traits , typename _Alloc > typedef iterator std::basic_string< _CharT, _Traits, _Alloc >::__const_iterator protected
Definition at line 146 of file cow_string.h.
allocator_type
template<typename _CharT , typename _Traits , typename _Alloc > typedef _Alloc std::basic_string< _CharT, _Traits, _Alloc >::allocator_type
Definition at line 126 of file cow_string.h.
const_iterator
template<typename _CharT , typename _Traits , typename _Alloc > typedef __gnu_cxx::__normal_iterator<const_pointer, basic_string> std::basic_string< _CharT, _Traits, _Alloc >::const_iterator
Definition at line 140 of file cow_string.h.
const_pointer
template<typename _CharT , typename _Traits , typename _Alloc > typedef _CharT_alloc_traits::const_pointer std::basic_string< _CharT, _Traits, _Alloc >::const_pointer
Definition at line 137 of file cow_string.h.
const_reference
template<typename _CharT , typename _Traits , typename _Alloc > typedef const value_type& std::basic_string< _CharT, _Traits, _Alloc >::const_reference
Definition at line 134 of file cow_string.h.
const_reverse_iterator
template<typename _CharT , typename _Traits , typename _Alloc > typedef std::reverse_iterator<const_iterator> std::basic_string< _CharT, _Traits, _Alloc >::const_reverse_iterator
Definition at line 141 of file cow_string.h.
difference_type
template<typename _CharT , typename _Traits , typename _Alloc > typedef _CharT_alloc_traits::difference_type std::basic_string< _CharT, _Traits, _Alloc >::difference_type
Definition at line 128 of file cow_string.h.
iterator
template<typename _CharT , typename _Traits , typename _Alloc > typedef __gnu_cxx::__normal_iterator<pointer, basic_string> std::basic_string< _CharT, _Traits, _Alloc >::iterator
Definition at line 138 of file cow_string.h.
pointer
template<typename _CharT , typename _Traits , typename _Alloc > typedef _CharT_alloc_traits::pointer std::basic_string< _CharT, _Traits, _Alloc >::pointer
Definition at line 136 of file cow_string.h.
reference
template<typename _CharT , typename _Traits , typename _Alloc > typedef value_type& std::basic_string< _CharT, _Traits, _Alloc >::reference
Definition at line 133 of file cow_string.h.
reverse_iterator
template<typename _CharT , typename _Traits , typename _Alloc > typedef std::reverse_iterator<iterator> std::basic_string< _CharT, _Traits, _Alloc >::reverse_iterator
Definition at line 142 of file cow_string.h.
size_type
template<typename _CharT , typename _Traits , typename _Alloc > typedef _CharT_alloc_traits::size_type std::basic_string< _CharT, _Traits, _Alloc >::size_type
Definition at line 127 of file cow_string.h.
traits_type
template<typename _CharT , typename _Traits , typename _Alloc > typedef _Traits std::basic_string< _CharT, _Traits, _Alloc >::traits_type
Definition at line 124 of file cow_string.h.
value_type
template<typename _CharT , typename _Traits , typename _Alloc > typedef _Traits::char_type std::basic_string< _CharT, _Traits, _Alloc >::value_type
Definition at line 125 of file cow_string.h.
Constructor & Destructor Documentation
basic_string() [1/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string () inline noexcept
Default constructor creates an empty string.
Definition at line 523 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::substr().
basic_string() [2/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _Alloc & __a) inline explicit
Construct an empty string using allocator a.
Definition at line 536 of file cow_string.h.
basic_string() [3/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Construct string with copy of value of str.
Parameters
__str Source string.
Definition at line 545 of file cow_string.h.
basic_string() [4/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos, const _Alloc & __a = _Alloc())
Construct string as copy of a substring.
Parameters
__str Source string.
__pos Index of first character to copy from.
__a Allocator to use.
Definition at line 3192 of file cow_string.h.
basic_string() [5/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos, size_type __n)
Construct string as copy of a substring.
Parameters
__str Source string.
__pos Index of first character to copy from.
__n Number of characters to copy.
Definition at line 3202 of file cow_string.h.
basic_string() [6/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos, size_type __n, const _Alloc & __a)
Construct string as copy of a substring.
Parameters
__str Source string.
__pos Index of first character to copy from.
__n Number of characters to copy.
__a Allocator to use.
Definition at line 3212 of file cow_string.h.
basic_string() [7/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _CharT * __s, size_type __n, const _Alloc & __a = _Alloc()) inline
Construct string initialized by a character array.
Parameters
__s Source character array.
__n Number of characters to copy.
__a Allocator to use (default is default allocator).
NB: __s must have at least __n characters, '\0' has no special meaning.
Definition at line 589 of file cow_string.h.
basic_string() [8/16]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename = _RequireAllocator<_Alloc>> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _CharT * __s, const _Alloc & __a = _Alloc()) inline
Construct string as copy of a C string.
Parameters
__s Source C string.
__a Allocator to use (default is default allocator).
Definition at line 604 of file cow_string.h.
basic_string() [9/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (size_type __n, _CharT __c, const _Alloc & __a = _Alloc()) inline
Construct string as multiple characters.
Parameters
__n Number of characters.
__c Character to use.
__a Allocator to use (default is default allocator).
Definition at line 615 of file cow_string.h.
basic_string() [10/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (basic_string< _CharT, _Traits, _Alloc > && __str) inline noexcept
Move construct string.
Parameters
__str Source string.
The newly-created string contains the exact contents of __str. __str is a valid, but unspecified string.
Definition at line 627 of file cow_string.h.
basic_string() [11/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (initializer_list< _CharT > __l, const _Alloc & __a = _Alloc()) inline
Construct string from an initializer list.
Parameters
__l std::initializer_list of characters.
__a Allocator to use (default is default allocator).
Definition at line 650 of file cow_string.h.
basic_string() [12/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const basic_string< _CharT, _Traits, _Alloc > & __str, const _Alloc & __a) inline
Definition at line 654 of file cow_string.h.
basic_string() [13/16]
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (basic_string< _CharT, _Traits, _Alloc > && __str, const _Alloc & __a) inline
Definition at line 658 of file cow_string.h.
basic_string() [14/16]
template<typename _CharT , typename _Traits , typename _Alloc > template<class _InputIterator > std::basic_string< _CharT, _Traits, _Alloc >::basic_string (_InputIterator __beg, _InputIterator __end, const _Alloc & __a = _Alloc()) inline
Construct string as copy of a range.
Parameters
__beg Start of range.
__end End of range.
__a Allocator to use (default is default allocator).
Definition at line 686 of file cow_string.h.
basic_string() [15/16]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp , typename = enable_if_t<is_convertible_v<const _Tp&, __sv_type>>> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _Tp & __t, size_type __pos, size_type __n, const _Alloc & __a = _Alloc()) inline
Construct string from a substring of a string_view.
Parameters
__t Source object convertible to string view.
__pos The index of the first character to copy from __t.
__n The number of characters to copy from __t.
__a Allocator to use.
Definition at line 701 of file cow_string.h.
basic_string() [16/16]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp , typename = _If_sv<_Tp, void>> std::basic_string< _CharT, _Traits, _Alloc >::basic_string (const _Tp & __t, const _Alloc & __a = _Alloc()) inline explicit
Construct string from a string_view.
Parameters
__t Source object convertible to string view.
__a Allocator to use (default is default allocator).
Definition at line 712 of file cow_string.h.
~basic_string()
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::~basic_string () inline noexcept
Destroy the string instance.
Definition at line 719 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::get_allocator().
Member Function Documentation
_M_replace_dispatch()
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _InputIterator > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::_M_replace_dispatch (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2, __false_type)
Definition at line 3649 of file cow_string.h.
_S_construct()
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _InIterator > _CharT * std::basic_string< _CharT, _Traits, _Alloc >::_S_construct (_InIterator __beg, _InIterator __end, const _Alloc & __a, forward_iterator_tag)
Definition at line 3146 of file cow_string.h.
append() [1/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<class _InputIterator > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::append (_InputIterator __first, _InputIterator __last) inline
Append a range of characters.
Parameters
__first Iterator referencing the first character to append.
__last Iterator marking the end of the range.
Returns
Reference to this string.
Appends characters in the range [__first,__last) to this string.
Definition at line 1299 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
append() [2/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::append (const _CharT * __s) inline
Append a C string.
Parameters
__s The C string to append.
Returns
Reference to this string.
Definition at line 1261 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
append() [3/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const _CharT * __s, size_type __n)
Append a C substring.
Parameters
__s The C string to append.
__n The number of characters to append.
Returns
Reference to this string.
Definition at line 3279 of file cow_string.h.
References std::size().
append() [4/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::append (const _Tp & __svt) inline
Append a string_view.
Parameters
__svt The object convertible to string_view to be appended.
Returns
Reference to this string.
Definition at line 1310 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
append() [5/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::append (const _Tp & __svt, size_type __pos, size_type __n = npos) inline
Append a range of characters from a string_view.
Parameters
__svt The object convertible to string_view to be appended from.
__pos The position in the string_view to append from.
__n The number of characters to append from the string_view.
Returns
Reference to this string.
Definition at line 1326 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
append() [6/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const basic_string< _CharT, _Traits, _Alloc > & __str)
Append a string to this string.
Parameters
__str The string to append.
Returns
Reference to this string.
Definition at line 3306 of file cow_string.h.
References std::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::operator+=(), std::basic_string< _CharT, _Traits, _Alloc >::operator+=(), std::basic_string< _CharT, _Traits, _Alloc >::operator+=(), and std::basic_string< _CharT, _Traits, _Alloc >::operator+=().
append() [7/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos, size_type __n = npos)
Append a substring.
Parameters
__str The string to append.
__pos Index of the first character of str to append.
__n The number of characters to append.
Returns
Reference to this string.
Exceptions
std::out_of_range if __pos is not a valid index.
This function appends __n characters from __str starting at __pos to this string. If __n is is larger than the number of available characters in __str, the remainder of __str is appended.
Definition at line 3323 of file cow_string.h.
References std::size().
append() [8/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::append (initializer_list< _CharT > __l) inline
Append an initializer_list of characters.
Parameters
__l The initializer_list of characters to append.
Returns
Reference to this string.
Definition at line 1285 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
append() [9/9]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::append (size_type __n, _CharT __c)
Append multiple characters.
Parameters
__n The number of characters to append.
__c The character to use.
Returns
Reference to this string.
Appends __n copies of __c to this string.
Definition at line 3262 of file cow_string.h.
References std::size().
assign() [1/10]
template<typename _CharT , typename _Traits , typename _Alloc > template<class _InputIterator > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (_InputIterator __first, _InputIterator __last) inline
Set value to a range of characters.
Parameters
__first Iterator referencing the first character to append.
__last Iterator marking the end of the range.
Returns
Reference to this string.
Sets value of string to characters in the range [__first,__last).
Definition at line 1446 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
assign() [2/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (basic_string< _CharT, _Traits, _Alloc > && __str) inline noexcept
Set value to contents of another string.
Parameters
__str Source string to use.
Returns
Reference to this string.
This function sets this string to the exact contents of __str. __str is a valid, but unspecified string.
Definition at line 1367 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::swap().
assign() [3/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (const _CharT * __s) inline
Set value to contents of a C string.
Parameters
__s The C string to use.
Returns
Reference to this string.
This function sets the value of this string to the value of __s. The data is copied, so there is no dependence on __s once the function returns.
Definition at line 1417 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
assign() [4/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::assign (const _CharT * __s, size_type __n)
Set value to a C substring.
Parameters
__s The C string to use.
__n Number of characters to use.
Returns
Reference to this string.
This function sets the value of this string to the first __n characters of __s. If __n is is larger than the number of available characters in __s, the remainder of __s is used.
Definition at line 3240 of file cow_string.h.
References std::size().
assign() [5/10]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::assign (const _Tp & __svt) inline
Set value from a string_view.
Parameters
__svt The source object convertible to string_view.
Returns
Reference to this string.
Definition at line 1468 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
assign() [6/10]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::assign (const _Tp & __svt, size_type __pos, size_type __n = npos) inline
Set value from a range of characters in a string_view.
Parameters
__svt The source object convertible to string_view.
__pos The position in the string_view to assign from.
__n The number of characters to assign.
Returns
Reference to this string.
Definition at line 1483 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
assign() [7/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::assign (const basic_string< _CharT, _Traits, _Alloc > & __str)
Set value to contents of another string.
Parameters
__str Source string to use.
Returns
Reference to this string.
Definition at line 3224 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::operator=(), std::basic_string< _CharT, _Traits, _Alloc >::operator=(), std::basic_string< _CharT, _Traits, _Alloc >::operator=(), std::basic_string< _CharT, _Traits, _Alloc >::operator=(), and std::basic_string< _CharT, _Traits, _Alloc >::operator=().
assign() [8/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos, size_type __n = npos) inline
Set value to a substring of a string.
Parameters
__str The string to use.
__pos Index of the first character of str.
__n Number of characters to use.
Returns
Reference to this string.
Exceptions
std::out_of_range if pos is not a valid index.
This function sets this string to the substring of __str consisting of __n characters at __pos. If __n is is larger than the number of available characters in __str, the remainder of __str is used.
Definition at line 1389 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
assign() [9/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (initializer_list< _CharT > __l) inline
Set value to an initializer_list of characters.
Parameters
__l The initializer_list of characters to assign.
Returns
Reference to this string.
Definition at line 1456 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
assign() [10/10]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::assign (size_type __n, _CharT __c) inline
Set value to multiple characters.
Parameters
__n Length of the resulting string.
__c The character to use.
Returns
Reference to this string.
This function sets the value of this string to __n copies of character __c.
Definition at line 1433 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
at() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reference std::basic_string< _CharT, _Traits, _Alloc >::at (size_type __n) inline
Provides access to the data contained in the string.
Parameters
__n The index of the character to access.
Returns
Read/write reference to the character.
Exceptions
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the string. The function throws out_of_range if the check fails. Success results in unsharing the string.
Definition at line 1111 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
at() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reference std::basic_string< _CharT, _Traits, _Alloc >::at (size_type __n) const inline
Provides access to the data contained in the string.
Parameters
__n The index of the character to access.
Returns
Read-only (const) reference to the character.
Exceptions
std::out_of_range If n is an invalid index.
This function provides for safer data access. The parameter is first checked that it is in the range of the string. The function throws out_of_range if the check fails.
Definition at line 1089 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
back() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reference std::basic_string< _CharT, _Traits, _Alloc >::back () inline
Returns a read/write reference to the data at the last element of the string.
Definition at line 1150 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), std::basic_string< _CharT, _Traits, _Alloc >::operator[](), and std::basic_string< _CharT, _Traits, _Alloc >::size().
back() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reference std::basic_string< _CharT, _Traits, _Alloc >::back () const inline noexcept
Returns a read-only (constant) reference to the data at the last element of the string.
Definition at line 1161 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), std::basic_string< _CharT, _Traits, _Alloc >::operator[](), and std::basic_string< _CharT, _Traits, _Alloc >::size().
begin() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > iterator std::basic_string< _CharT, _Traits, _Alloc >::begin () inline
Returns a read/write iterator that points to the first character in the string. Unshares the string.
Definition at line 805 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::crend(), std::basic_string< _CharT, _Traits, _Alloc >::rend(), std::basic_string< _CharT, _Traits, _Alloc >::rend(), and std::basic_string< _CharT, _Traits, _Alloc >::replace().
begin() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_iterator std::basic_string< _CharT, _Traits, _Alloc >::begin () const inline noexcept
Returns a read-only (constant) iterator that points to the first character in the string.
Definition at line 816 of file cow_string.h.
c_str()
template<typename _CharT , typename _Traits , typename _Alloc > const _CharT * std::basic_string< _CharT, _Traits, _Alloc >::c_str () const inline noexcept
Return const pointer to null-terminated contents.
This is a handle to internal data. Do not modify or dire things may happen.
Definition at line 2215 of file cow_string.h.
Referenced by std::experimental::filesystem::v1::filesystem_error::what().
capacity()
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::capacity () const inline noexcept
Returns the total number of characters that the string can hold before needing to allocate more memory.
Definition at line 978 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::push_back().
cbegin()
template<typename _CharT , typename _Traits , typename _Alloc > const_iterator std::basic_string< _CharT, _Traits, _Alloc >::cbegin () const inline noexcept
Returns a read-only (constant) iterator that points to the first character in the string.
Definition at line 880 of file cow_string.h.
cend()
template<typename _CharT , typename _Traits , typename _Alloc > const_iterator std::basic_string< _CharT, _Traits, _Alloc >::cend () const inline noexcept
Returns a read-only (constant) iterator that points one past the last character in the string.
Definition at line 888 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
clear()
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::clear () inline noexcept
Erases the string, making it empty.
Definition at line 1013 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::get_allocator().
compare() [1/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (const _CharT * __s) const inline noexcept
Compare to a C string.
Parameters
__s C string to compare against.
Returns
Integer < 0, 0, or > 0.
Returns an integer < 0 if this string is ordered before __s, 0 if their values are equivalent, or > 0 if this string is ordered after __s. Determines the effective length rlen of the strings to compare as the smallest of size() and the length of a string constructed from __s. The function then compares the two strings by calling traits::compare(data(),s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2930 of file cow_string.h.
References std::min(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
compare() [2/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, int > std::basic_string< _CharT, _Traits, _Alloc >::compare (const _Tp & __svt) const inline noexcept
Compare to a string_view.
Parameters
__svt An object convertible to string_view to compare against.
Returns
Integer < 0, 0, or > 0.
Definition at line 2791 of file cow_string.h.
References std::min(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
compare() [3/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (const basic_string< _CharT, _Traits, _Alloc > & __str) const inline
Compare to a string.
Parameters
__str String to compare against.
Returns
Integer < 0, 0, or > 0.
Returns an integer < 0 if this string is ordered before __str, 0 if their values are equivalent, or > 0 if this string is ordered after __str. Determines the effective length rlen of the strings to compare as the smallest of size() and str.size(). The function then compares the two strings by calling traits::compare(data(), str.data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2771 of file cow_string.h.
References std::min(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
compare() [4/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, int > std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos, size_type __n, const _Tp & __svt) const inline noexcept
Compare to a string_view.
Parameters
__pos A position in the string to start comparing from.
__n The number of characters to compare.
__svt An object convertible to string_view to compare against.
Returns
Integer < 0, 0, or > 0.
Definition at line 2815 of file cow_string.h.
compare() [5/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos, size_type __n, const basic_string< _CharT, _Traits, _Alloc > & __str) const inline
Compare substring to a string.
Parameters
__pos Index of first character of substring.
__n Number of characters in substring.
__str String to compare against.
Returns
Integer < 0, 0, or > 0.
Form the substring of this string from the __n characters starting at __pos. Returns an integer < 0 if the substring is ordered before __str, 0 if their values are equivalent, or > 0 if the substring is ordered after __str. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and __str.size(). The function then compares the two strings by calling traits::compare(substring.data(),str.data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2864 of file cow_string.h.
References std::min().
compare() [6/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos, size_type __n1, const _CharT * __s) const inline
Compare substring to a C string.
Parameters
__pos Index of first character of substring.
__n1 Number of characters in substring.
__s C string to compare against.
Returns
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at pos. Returns an integer < 0 if the substring is ordered before __s, 0 if their values are equivalent, or > 0 if the substring is ordered after __s. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and the length of a string constructed from __s. The function then compares the two string by calling traits::compare(substring.data(),__s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2964 of file cow_string.h.
References std::min().
compare() [7/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos, size_type __n1, const _CharT * __s, size_type __n2) const inline
Compare substring against a character array.
Parameters
__pos Index of first character of substring.
__n1 Number of characters in substring.
__s character array to compare against.
__n2 Number of characters of s.
Returns
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at __pos. Form a string from the first __n2 characters of __s. Returns an integer < 0 if this substring is ordered before the string from __s, 0 if their values are equivalent, or > 0 if this substring is ordered after the string from __s. Determines the effective length rlen of the strings to compare as the smallest of the length of the substring and __n2. The function then compares the two strings by calling traits::compare(substring.data(),s,rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
NB: s must have at least n2 characters, '\0' has no special meaning.
Definition at line 3002 of file cow_string.h.
References std::min().
compare() [8/9]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, int > std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos1, size_type __n1, const _Tp & __svt, size_type __pos2, size_type __n2 = npos) const inline noexcept
Compare to a string_view.
Parameters
__pos1 A position in the string to start comparing from.
__n1 The number of characters to compare.
__svt An object convertible to string_view to compare against.
__pos2 A position in the string_view to start comparing from.
__n2 The number of characters to compare.
Returns
Integer < 0, 0, or > 0.
Definition at line 2834 of file cow_string.h.
compare() [9/9]
template<typename _CharT , typename _Traits , typename _Alloc > int std::basic_string< _CharT, _Traits, _Alloc >::compare (size_type __pos1, size_type __n1, const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos2, size_type __n2 = npos) const inline
Compare substring to a substring.
Parameters
__pos1 Index of first character of substring.
__n1 Number of characters in substring.
__str String to compare against.
__pos2 Index of first character of substring of str.
__n2 Number of characters in substring of str.
Returns
Integer < 0, 0, or > 0.
Form the substring of this string from the __n1 characters starting at __pos1. Form the substring of __str from the __n2 characters starting at __pos2. Returns an integer < 0 if this substring is ordered before the substring of __str, 0 if their values are equivalent, or > 0 if this substring is ordered after the substring of __str. Determines the effective length rlen of the strings to compare as the smallest of the lengths of the substrings. The function then compares the two strings by calling traits::compare(substring.data(),str.substr(pos2,n2).data(),rlen). If the result of the comparison is nonzero returns it, otherwise the shorter one is ordered first.
Definition at line 2900 of file cow_string.h.
References std::min().
copy()
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::copy (_CharT * __s, size_type __n, size_type __pos = 0) const
Copy substring into C string.
Parameters
__s C string to copy value into.
__n Number of characters to copy.
__pos Index of first character to copy.
Returns
Number of characters actually copied
Exceptions
std::out_of_range If __pos > size().
Copies up to __n characters starting at __pos into the C string __s. If __pos is greater than size(), out_of_range is thrown.
Definition at line 3708 of file cow_string.h.
crbegin()
template<typename _CharT , typename _Traits , typename _Alloc > const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::crbegin () const inline noexcept
Returns a read-only (constant) reverse iterator that points to the last character in the string. Iteration is done in reverse element order.
Definition at line 897 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::end().
crend()
template<typename _CharT , typename _Traits , typename _Alloc > const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::crend () const inline noexcept
Returns a read-only (constant) reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order.
Definition at line 906 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin().
data() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > const _CharT * std::basic_string< _CharT, _Traits, _Alloc >::data () const inline noexcept
Return const pointer to contents.
This is a pointer to internal data. It is undefined to modify the contents through the returned pointer. To get a pointer that allows modifying the contents use &str[0] instead, (or in C++17 the non-const str.data() overload).
Definition at line 2227 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_of(), std::basic_string< _CharT, _Traits, _Alloc >::operator __sv_type(), and std::basic_string< _CharT, _Traits, _Alloc >::rfind().
data() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > _CharT * std::basic_string< _CharT, _Traits, _Alloc >::data () inline noexcept
Return non-const pointer to contents.
This is a pointer to the character sequence held by the string. Modifying the characters in the sequence is allowed.
Definition at line 2238 of file cow_string.h.
empty()
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::empty () const inline noexcept
Returns true if the string is empty. Equivalent to *this == "".
Definition at line 1035 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::front(), std::basic_string< _CharT, _Traits, _Alloc >::front(), and std::basic_string< _CharT, _Traits, _Alloc >::pop_back().
end() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > iterator std::basic_string< _CharT, _Traits, _Alloc >::end () inline
Returns a read/write iterator that points one past the last character in the string. Unshares the string.
Definition at line 824 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::crbegin(), std::basic_string< _CharT, _Traits, _Alloc >::rbegin(), and std::basic_string< _CharT, _Traits, _Alloc >::rbegin().
end() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_iterator std::basic_string< _CharT, _Traits, _Alloc >::end () const inline noexcept
Returns a read-only (constant) iterator that points one past the last character in the string.
Definition at line 835 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
ends_with() [1/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::ends_with (_CharT __x) const inline noexcept
Definition at line 3034 of file cow_string.h.
ends_with() [2/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::ends_with (basic_string_view< _CharT, _Traits > __x) const inline noexcept
Definition at line 3030 of file cow_string.h.
ends_with() [3/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::ends_with (const _CharT * __x) const inline noexcept
Definition at line 3039 of file cow_string.h.
erase() [1/3]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::iterator std::basic_string< _CharT, _Traits, _Alloc >::erase (iterator __first, iterator __last)
Remove a range of characters.
Parameters
__first Iterator referencing the first character to remove.
__last Iterator referencing the end of the range.
Returns
Iterator referencing location of first after removal.
Removes the characters in the range [first,last) from this string. The value of the string doesn't change if an error is thrown.
Definition at line 3372 of file cow_string.h.
erase() [2/3]
template<typename _CharT , typename _Traits , typename _Alloc > iterator std::basic_string< _CharT, _Traits, _Alloc >::erase (iterator __position) inline
Remove one character.
Parameters
__position Iterator referencing the character to remove.
Returns
iterator referencing same location after removal.
Removes the character at __position from this string. The value of the string doesn't change if an error is thrown.
Definition at line 1734 of file cow_string.h.
erase() [3/3]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::erase (size_type __pos = 0, size_type __n = npos) inline
Remove characters.
Parameters
__pos Index of first character to remove (default 0).
__n Number of characters to remove (default remainder).
Returns
Reference to this string.
Exceptions
std::out_of_range If pos is beyond the end of this string.
Removes __n characters from this string starting at __pos. The length of the string is reduced by __n. If there are < __n characters to remove, the remainder of the string is truncated. If __p is beyond end of string, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1718 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::pop_back().
find() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find (_CharT __c, size_type __pos = 0) const noexcept
Find position of a character.
Parameters
__c Character to locate.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 655 of file basic_string.tcc.
References std::size().
find() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find position of a C substring.
Parameters
__s C string to locate.
__pos Index of character to search from.
__n Number of characters from s to search for.
Returns
Index of start of first occurrence.
Starting from __pos, searches forward for the first __n characters in __s within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 618 of file basic_string.tcc.
References std::data(), and std::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find(), std::basic_string< _CharT, _Traits, _Alloc >::find(), std::basic_string< _CharT, _Traits, _Alloc >::find(), and std::basic_string< _CharT, _Traits, _Alloc >::find_first_of().
find() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const _CharT * __s, size_type __pos = 0) const inline noexcept
Find position of a C string.
Parameters
__s C string to locate.
__pos Index of character to search from (default 0).
Returns
Index of start of first occurrence.
Starting from __pos, searches forward for the value of __s within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 2294 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find().
find() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::find (const _Tp & __svt, size_type __pos = 0) const inline noexcept
Find position of a string_view.
Parameters
__svt The object convertible to string_view to locate.
__pos Index of character to search from (default 0).
Returns
Index of start of first occurrence.
Definition at line 2322 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find().
find() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = 0) const inline noexcept
Find position of a string.
Parameters
__str String to locate.
__pos Index of character to search from (default 0).
Returns
Index of start of first occurrence.
Starting from __pos, searches forward for value of __str within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 2279 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::find().
find_first_not_of() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (_CharT __c, size_type __pos = 0) const noexcept
Find position of a different character.
Parameters
__c Character to avoid.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for a character other than __c within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 769 of file basic_string.tcc.
References std::size().
find_first_not_of() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find position of a character not in C substring.
Parameters
__s C string containing characters to avoid.
__pos Index of character to search from.
__n Number of characters from __s to consider.
Returns
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 755 of file basic_string.tcc.
References std::size().
find_first_not_of() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const _CharT * __s, size_type __pos = 0) const inline noexcept
Find position of a character not in C string.
Parameters
__s C string containing characters to avoid.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2618 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of().
find_first_not_of() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const _Tp & __svt, size_type __pos = 0) const inline noexcept
Find position of a character not in a string_view.
Parameters
__svt An object convertible to string_view containing characters to avoid.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Definition at line 2649 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of().
find_first_not_of() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = 0) const inline noexcept
Find position of a character not in string.
Parameters
__str String containing characters to avoid.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for a character not contained in __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2587 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of(), and std::basic_string< _CharT, _Traits, _Alloc >::find_first_not_of().
find_first_of() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (_CharT __c, size_type __pos = 0) const inline noexcept
Find position of a character.
Parameters
__c Character to locate.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for the character __c within this string. If found, returns the index where it was found. If not found, returns npos.
Note: equivalent to find(__c, __pos).
Definition at line 2471 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find().
find_first_of() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find position of a character of C substring.
Parameters
__s String containing characters to locate.
__pos Index of character to search from.
__n Number of characters from s to search for.
Returns
Index of first occurrence.
Starting from __pos, searches forward for one of the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 715 of file basic_string.tcc.
References std::size().
find_first_of() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const _CharT * __s, size_type __pos = 0) const inline noexcept
Find position of a character of C string.
Parameters
__s String containing characters to locate.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for one of the characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2451 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_first_of().
find_first_of() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const _Tp & __svt, size_type __pos = 0) const inline noexcept
Find position of a character of a string_view.
Parameters
__svt An object convertible to string_view containing characters to locate.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Definition at line 2484 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_first_of().
find_first_of() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_first_of (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = 0) const inline noexcept
Find position of a character of string.
Parameters
__str String containing characters to locate.
__pos Index of character to search from (default 0).
Returns
Index of first occurrence.
Starting from __pos, searches forward for one of the characters of __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2420 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::find_first_of().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find_first_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_first_of(), and std::basic_string< _CharT, _Traits, _Alloc >::find_first_of().
find_last_not_of() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (_CharT __c, size_type __pos = npos) const noexcept
Find last position of a different character.
Parameters
__c Character to avoid.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for a character other than __c within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 804 of file basic_string.tcc.
References std::size().
find_last_not_of() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find last position of a character not in C substring.
Parameters
__s C string containing characters to avoid.
__pos Index of character to search back from.
__n Number of characters from s to consider.
Returns
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 781 of file basic_string.tcc.
References std::size().
find_last_not_of() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const _CharT * __s, size_type __pos = npos) const inline noexcept
Find last position of a character not in C string.
Parameters
__s C string containing characters to avoid.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2700 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of().
find_last_not_of() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const _Tp & __svt, size_type __pos = npos) const inline noexcept
Find last position of a character not in a string_view.
Parameters
__svt An object convertible to string_view containing characters to avoid.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Definition at line 2731 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of().
find_last_not_of() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = npos) const inline noexcept
Find last position of a character not in string.
Parameters
__str String containing characters to avoid.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for a character not contained in __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2669 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of(), and std::basic_string< _CharT, _Traits, _Alloc >::find_last_not_of().
find_last_of() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (_CharT __c, size_type __pos = npos) const inline noexcept
Find last position of a character.
Parameters
__c Character to locate.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Note: equivalent to rfind(__c, __pos).
Definition at line 2555 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::rfind().
find_last_of() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find last position of a character of C substring.
Parameters
__s C string containing characters to locate.
__pos Index of character to search back from.
__n Number of characters from s to search for.
Returns
Index of last occurrence.
Starting from __pos, searches backward for one of the first __n characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 732 of file basic_string.tcc.
References std::size().
find_last_of() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const _CharT * __s, size_type __pos = npos) const inline noexcept
Find last position of a character of C string.
Parameters
__s C string containing characters to locate.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for one of the characters of __s within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2535 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_last_of().
find_last_of() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const _Tp & __svt, size_type __pos = npos) const inline noexcept
Find last position of a character of string.
Parameters
__svt An object convertible to string_view containing characters to locate.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Definition at line 2568 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::find_last_of().
find_last_of() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::find_last_of (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = npos) const inline noexcept
Find last position of a character of string.
Parameters
__str String containing characters to locate.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for one of the characters of __str within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 2504 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::find_last_of().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find_last_of(), std::basic_string< _CharT, _Traits, _Alloc >::find_last_of(), and std::basic_string< _CharT, _Traits, _Alloc >::find_last_of().
front() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reference std::basic_string< _CharT, _Traits, _Alloc >::front () inline
Returns a read/write reference to the data at the first element of the string.
Definition at line 1128 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), and std::basic_string< _CharT, _Traits, _Alloc >::operator[]().
front() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reference std::basic_string< _CharT, _Traits, _Alloc >::front () const inline noexcept
Returns a read-only (constant) reference to the data at the first element of the string.
Definition at line 1139 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), and std::basic_string< _CharT, _Traits, _Alloc >::operator[]().
get_allocator()
template<typename _CharT , typename _Traits , typename _Alloc > allocator_type std::basic_string< _CharT, _Traits, _Alloc >::get_allocator () const inline noexcept
Return copy of allocator used to construct this string.
Definition at line 2249 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::~basic_string(), and std::basic_string< _CharT, _Traits, _Alloc >::clear().
insert() [1/11]
template<typename _CharT , typename _Traits , typename _Alloc > iterator std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator __p, _CharT __c) inline
Insert one character.
Parameters
__p Iterator referencing position in string to insert at.
__c The character to insert.
Returns
Iterator referencing newly inserted char.
Exceptions
std::length_error If new length exceeds max_size().
Inserts character __c at position referenced by __p. If adding character causes the length to exceed max_size(), length_error is thrown. If __p is beyond end of string, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1658 of file cow_string.h.
insert() [2/11]
template<typename _CharT , typename _Traits , typename _Alloc > template<class _InputIterator > void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator __p, _InputIterator __beg, _InputIterator __end) inline
Insert a range of characters.
Parameters
__p Iterator referencing location in string to insert at.
__beg Start of range.
__end End of range.
Exceptions
std::length_error If new length exceeds max_size().
Inserts characters in range [__beg,__end). If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1523 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
insert() [3/11]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator __p, initializer_list< _CharT > __l) inline
Insert an initializer_list of characters.
Parameters
__p Iterator referencing location in string to insert at.
__l The initializer_list of characters to insert.
Exceptions
std::length_error If new length exceeds max_size().
Definition at line 1534 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::insert().
insert() [4/11]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::insert (iterator __p, size_type __n, _CharT __c) inline
Insert multiple characters.
Parameters
__p Iterator referencing location in string to insert at.
__n Number of characters to insert
__c The character to insert.
Exceptions
std::length_error If new length exceeds max_size().
Inserts __n copies of character __c starting at the position referenced by iterator __p. If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1506 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), and std::basic_string< _CharT, _Traits, _Alloc >::insert().
insert() [5/11]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos, const _CharT * __s) inline
Insert a C string.
Parameters
__pos Position in string to insert at.
__s The C string to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
std::out_of_range If pos is beyond the end of this string.
Inserts the first n characters of __s starting at __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1617 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::insert().
insert() [6/11]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos, const _CharT * __s, size_type __n)
Insert a C substring.
Parameters
__pos Position in string to insert at.
__s The C string to insert.
__n The number of characters to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
std::out_of_range If __pos is beyond the end of this string.
Inserts the first __n characters of __s starting at __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos is beyond end(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 3341 of file cow_string.h.
insert() [7/11]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos, const _Tp & __svt) inline
Insert a string_view.
Parameters
__pos Position in string to insert at.
__svt The object convertible to string_view to insert.
Returns
Reference to this string.
Definition at line 1676 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::insert().
insert() [8/11]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos, size_type __n, _CharT __c) inline
Insert multiple characters.
Parameters
__pos Index in string to insert at.
__n Number of characters to insert
__c The character to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
std::out_of_range If __pos is beyond the end of this string.
Inserts __n copies of character __c starting at index __pos. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos > length(), out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1640 of file cow_string.h.
insert() [9/11]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos1, const _Tp & __svt, size_type __pos2, size_type __n = npos) inline
Insert a string_view.
Parameters
__pos1 Position in string to insert at.
__svt The object convertible to string_view to insert from.
__pos2 Position in string_view to insert from.
__n The number of characters to insert.
Returns
Reference to this string.
Definition at line 1692 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
insert() [10/11]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos1, const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Insert value of a string.
Parameters
__pos1 Position in string to insert at.
__str The string to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Inserts value of __str starting at __pos1. If adding characters causes the length to exceed max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1554 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::insert().
insert() [11/11]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::insert (size_type __pos1, const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos2, size_type __n = npos) inline
Insert a substring.
Parameters
__pos1 Position in string to insert at.
__str The string to insert.
__pos2 Start of characters in str to insert.
__n Number of characters to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
std::out_of_range If pos1 > size() or __pos2 > str.size().
Starting at pos1, insert __n character of __str beginning with __pos2. If adding characters causes the length to exceed max_size(), length_error is thrown. If __pos1 is beyond the end of this string or __pos2 is beyond the end of __str, out_of_range is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1576 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::insert().
length()
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::length () const inline noexcept
Returns the number of characters in the string, not including any null-termination.
Definition at line 928 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
max_size()
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::max_size () const inline noexcept
Returns the size() of the largest possible string.
Definition at line 933 of file cow_string.h.
operator __sv_type()
template<typename _CharT , typename _Traits , typename _Alloc > std::basic_string< _CharT, _Traits, _Alloc >::operator __sv_type () const inline noexcept
Convert to a string_view.
Returns
A string_view.
Definition at line 795 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
operator+=() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator+= (_CharT __c) inline
Append a character.
Parameters
__c The character to append.
Returns
Reference to this string.
Definition at line 1193 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::push_back().
operator+=() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator+= (const _CharT * __s) inline
Append a C string.
Parameters
__s The C string to append.
Returns
Reference to this string.
Definition at line 1184 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
operator+=() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::operator+= (const _Tp & __svt) inline
Append a string_view.
Parameters
__svt The object convertible to string_view to be appended.
Returns
Reference to this string.
Definition at line 1218 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
operator+=() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator+= (const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Append a string to this string.
Parameters
__str The string to append.
Returns
Reference to this string.
Definition at line 1175 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
operator+=() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator+= (initializer_list< _CharT > __l) inline
Append an initializer_list of characters.
Parameters
__l The initializer_list of characters to be appended.
Returns
Reference to this string.
Definition at line 1206 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::append().
operator=() [1/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator= (_CharT __c) inline
Set value to string of length 1.
Parameters
__c Source character.
Assigning to a character makes this string length 1 and (*this)[0] == c.
Definition at line 746 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
operator=() [2/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator= (basic_string< _CharT, _Traits, _Alloc > && __str) inline noexcept
Move assign the value of str to this string.
Parameters
__str Source string.
The contents of str are moved into this string (without copying). str is a valid, but unspecified string.
Definition at line 761 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::swap().
operator=() [3/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator= (const _CharT * __s) inline
Copy contents of s into this string.
Parameters
__s Source null-terminated string.
Definition at line 735 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
operator=() [4/6]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::operator= (const _Tp & __svt) inline
Set value to string constructed from a string_view.
Parameters
__svt An object convertible to string_view.
Definition at line 788 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
operator=() [5/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator= (const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Assign the value of str to this string.
Parameters
__str Source string.
Definition at line 727 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
operator=() [6/6]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::operator= (initializer_list< _CharT > __l) inline
Set value to string constructed from initializer list.
Parameters
__l std::initializer_list.
Definition at line 774 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::assign().
operator[]() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reference std::basic_string< _CharT, _Traits, _Alloc >::operator[] (size_type __pos) inline
Subscript access to the data contained in the string.
Parameters
__pos The index of the character to access.
Returns
Read/write reference to the character.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().) Unshares the string.
Definition at line 1067 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
operator[]() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reference std::basic_string< _CharT, _Traits, _Alloc >::operator[] (size_type __pos) const inline noexcept
Subscript access to the data contained in the string.
Parameters
__pos The index of the character to access.
Returns
Read-only (constant) reference to the character.
This operator allows for easy, array-style, data access. Note that data access with this operator is unchecked and out_of_range lookups are not defined. (For checked lookups see at().)
Definition at line 1050 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::front(), and std::basic_string< _CharT, _Traits, _Alloc >::front().
pop_back()
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::pop_back () inline
Remove the last character.
The string must be non-empty.
Definition at line 1763 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::empty(), std::basic_string< _CharT, _Traits, _Alloc >::erase(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
push_back()
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::push_back (_CharT __c) inline
Append a single character.
Parameters
__c Character to append.
Definition at line 1340 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::capacity(), std::basic_string< _CharT, _Traits, _Alloc >::reserve(), and std::basic_string< _CharT, _Traits, _Alloc >::size().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::operator+=().
rbegin() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rbegin () inline
Returns a read/write reverse iterator that points to the last character in the string. Iteration is done in reverse element order. Unshares the string.
Definition at line 844 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::end().
rbegin() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rbegin () const inline noexcept
Returns a read-only (constant) reverse iterator that points to the last character in the string. Iteration is done in reverse element order.
Definition at line 853 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::end().
rend() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rend () inline
Returns a read/write reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order. Unshares the string.
Definition at line 862 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin().
rend() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > const_reverse_iterator std::basic_string< _CharT, _Traits, _Alloc >::rend () const inline noexcept
Returns a read-only (constant) reverse iterator that points to one before the first character in the string. Iteration is done in reverse element order.
Definition at line 871 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin().
replace() [1/18]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::replace (const_iterator __i1, const_iterator __i2, const _Tp & __svt) inline
Replace range of characters with string_view.
Parameters
__i1 An iterator referencing the start position to replace at.
__i2 An iterator referencing the end position for the replace.
__svt The object convertible to string_view to insert from.
Returns
Reference to this string.
Definition at line 2104 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::begin(), and std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [2/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, _CharT * __k1, _CharT * __k2) inline
Definition at line 1995 of file cow_string.h.
replace() [3/18]
template<typename _CharT , typename _Traits , typename _Alloc > template<class _InputIterator > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, _InputIterator __k1, _InputIterator __k2) inline
Replace range of characters with range.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__k1 Iterator referencing start of range to insert.
__k2 Iterator referencing end of range to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, characters in the range [__k1,__k2) are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1982 of file cow_string.h.
replace() [4/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, const _CharT * __k1, const _CharT * __k2) inline
Definition at line 2005 of file cow_string.h.
replace() [5/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, const _CharT * __s) inline
Replace range of characters with C string.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__s C string value to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the characters of __s are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1937 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [6/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, const _CharT * __s, size_type __n) inline
Replace range of characters with C substring.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__s C string value to insert.
__n Number of characters from s to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the first __n characters of __s are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1916 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [7/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Replace range of characters with string.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__str String value to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, the value of __str is inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1897 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [8/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, const_iterator __k1, const_iterator __k2) inline
Definition at line 2026 of file cow_string.h.
replace() [9/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, initializer_list< _CharT > __l) inline
Replace range of characters with initializer_list.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__l The initializer_list of characters to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, characters in the range [__k1,__k2) are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 2051 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [10/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, iterator __k1, iterator __k2) inline
Definition at line 2016 of file cow_string.h.
replace() [11/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (iterator __i1, iterator __i2, size_type __n, _CharT __c) inline
Replace range of characters with multiple characters.
Parameters
__i1 Iterator referencing start of range to replace.
__i2 Iterator referencing end of range to replace.
__n Number of characters to insert.
__c Character to insert.
Returns
Reference to this string.
Exceptions
std::length_error If new length exceeds max_size().
Removes the characters in the range [__i1,__i2). In place, __n copies of __c are inserted. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1958 of file cow_string.h.
replace() [12/18]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos, size_type __n, const _Tp & __svt) inline
Replace range of characters with string_view.
Parameters
__pos The position to replace at.
__n The number of characters to replace.
__svt The object convertible to string_view to insert.
Returns
Reference to this string.
Definition at line 2066 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [13/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos, size_type __n, const basic_string< _CharT, _Traits, _Alloc > & __str) inline
Replace characters with value from another string.
Parameters
__pos Index of first character to replace.
__n Number of characters to be replaced.
__str String to insert.
Returns
Reference to this string.
Exceptions
std::out_of_range If pos is beyond the end of this string.
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos+__n) from this string. In place, the value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of the result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1788 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::append(), std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::insert(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), std::basic_string< _CharT, _Traits, _Alloc >::replace(), and std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [14/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos, size_type __n1, const _CharT * __s) inline
Replace characters with value of a C string.
Parameters
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__s C string to insert.
Returns
Reference to this string.
Exceptions
std::out_of_range If pos > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos + __n1) from this string. In place, the characters of __s are inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1855 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [15/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc > & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos, size_type __n1, const _CharT * __s, size_type __n2)
Replace characters with value of a C substring.
Parameters
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__s C string to insert.
__n2 Number of characters from s to use.
Returns
Reference to this string.
Exceptions
std::out_of_range If pos1 > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos,__pos + __n1) from this string. In place, the first __n2 characters of __s are inserted, or all of __s if __n2 is too large. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 3395 of file cow_string.h.
replace() [16/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos, size_type __n1, size_type __n2, _CharT __c) inline
Replace characters with multiple characters.
Parameters
__pos Index of first character to replace.
__n1 Number of characters to be replaced.
__n2 Number of characters to insert.
__c Character to insert.
Returns
Reference to this string.
Exceptions
std::out_of_range If __pos > size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [pos,pos + n1) from this string. In place, __n2 copies of __c are inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1879 of file cow_string.h.
replace() [17/18]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, basic_string & > std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos1, size_type __n1, const _Tp & __svt, size_type __pos2, size_type __n2 = npos) inline
Replace range of characters with string_view.
Parameters
__pos1 The position to replace at.
__n1 The number of characters to replace.
__svt The object convertible to string_view to insert from.
__pos2 The position in the string_view to insert from.
__n2 The number of characters to insert.
Returns
Reference to this string.
Definition at line 2083 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
replace() [18/18]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string & std::basic_string< _CharT, _Traits, _Alloc >::replace (size_type __pos1, size_type __n1, const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos2, size_type __n2 = npos) inline
Replace characters with value from another string.
Parameters
__pos1 Index of first character to replace.
__n1 Number of characters to be replaced.
__str String to insert.
__pos2 Index of first character of str to use.
__n2 Number of characters from str to use.
Returns
Reference to this string.
Exceptions
std::out_of_range If __pos1 > size() or __pos2 > __str.size().
std::length_error If new length exceeds max_size().
Removes the characters in the range [__pos1,__pos1 + n) from this string. In place, the value of __str is inserted. If __pos is beyond end of string, out_of_range is thrown. If the length of the result exceeds max_size(), length_error is thrown. The value of the string doesn't change if an error is thrown.
Definition at line 1810 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::replace().
reserve() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::reserve ()
Equivalent to shrink_to_fit().
Definition at line 3687 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::push_back(), and std::basic_string< _CharT, _Traits, _Alloc >::shrink_to_fit().
reserve() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::reserve (size_type __res_arg)
Attempt to preallocate enough memory for specified number of characters.
Parameters
__res_arg Number of characters required.
Exceptions
std::length_error If __res_arg exceeds max_size().
This function attempts to reserve enough memory for the string to hold the specified number of characters. If the number requested is more than max_size(), length_error is thrown.
The advantage of this function is that if optimal code is a necessity and the user can determine the string length that will be required, the user can reserve the memory in advance, and thus prevent a possible reallocation of memory and copying of string data.
Definition at line 3486 of file cow_string.h.
References std::size().
resize() [1/2]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::resize (size_type __n) inline
Resizes the string to the specified number of characters.
Parameters
__n Number of characters the string should contain.
This function will resize the string to the specified length. If the new size is smaller than the string's current size the string is truncated, otherwise the string is extended and new characters are default-constructed. For basic types such as char, this means setting them to 0.
Definition at line 960 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::resize().
resize() [2/2]
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::resize (size_type __n, _CharT __c)
Resizes the string to the specified number of characters.
Parameters
__n Number of characters the string should contain.
__c Character to fill any new elements.
This function will resize the string to the specified number of characters. If the number is smaller than the string's current size the string is truncated, otherwise the string is extended and new elements are set to __c.
Definition at line 3634 of file cow_string.h.
References std::size().
Referenced by std::money_get< _CharT, _InIter >::do_get(), and std::basic_string< _CharT, _Traits, _Alloc >::resize().
rfind() [1/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (_CharT __c, size_type __pos = npos) const noexcept
Find last position of a character.
Parameters
__c Character to locate.
__pos Index of character to search back from (default end).
Returns
Index of last occurrence.
Starting from __pos, searches backward for __c within this string. If found, returns the index where it was found. If not found, returns npos.
Definition at line 697 of file basic_string.tcc.
References std::size().
rfind() [2/5]
template<typename _CharT , typename _Traits , typename _Alloc > basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const _CharT * __s, size_type __pos, size_type __n) const noexcept
Find last position of a C substring.
Parameters
__s C string to locate.
__pos Index of character to search back from.
__n Number of characters from s to search for.
Returns
Index of start of last occurrence.
Starting from __pos, searches backward for the first __n characters in __s within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 674 of file basic_string.tcc.
References std::min(), and std::size().
rfind() [3/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const _CharT * __s, size_type __pos = npos) const inline noexcept
Find last position of a C string.
Parameters
__s C string to locate.
__pos Index of character to start search at (default end).
Returns
Index of start of last occurrence.
Starting from __pos, searches backward for the value of __s within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 2372 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::rfind().
rfind() [4/5]
template<typename _CharT , typename _Traits , typename _Alloc > template<typename _Tp > _If_sv< _Tp, size_type > std::basic_string< _CharT, _Traits, _Alloc >::rfind (const _Tp & __svt, size_type __pos = npos) const inline noexcept
Find last position of a string_view.
Parameters
__svt The object convertible to string_view to locate.
__pos Index of character to search back from (default end).
Returns
Index of start of last occurrence.
Definition at line 2400 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::rfind().
rfind() [5/5]
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::rfind (const basic_string< _CharT, _Traits, _Alloc > & __str, size_type __pos = npos) const inline noexcept
Find last position of a string.
Parameters
__str String to locate.
__pos Index of character to search back from (default end).
Returns
Index of start of last occurrence.
Starting from __pos, searches backward for value of __str within this string. If found, returns the index where it begins. If not found, returns npos.
Definition at line 2341 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::data(), and std::basic_string< _CharT, _Traits, _Alloc >::rfind().
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::find_last_of(), std::basic_string< _CharT, _Traits, _Alloc >::rfind(), std::basic_string< _CharT, _Traits, _Alloc >::rfind(), and std::basic_string< _CharT, _Traits, _Alloc >::rfind().
shrink_to_fit()
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::shrink_to_fit () inline noexcept
A non-binding request to reduce capacity() to size().
Definition at line 968 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::reserve().
size()
template<typename _CharT , typename _Traits , typename _Alloc > size_type std::basic_string< _CharT, _Traits, _Alloc >::size () const inline noexcept
Returns the number of characters in the string, not including any null-termination.
Definition at line 916 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::assign(), std::basic_string< _CharT, _Traits, _Alloc >::at(), std::basic_string< _CharT, _Traits, _Alloc >::at(), std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::back(), std::basic_string< _CharT, _Traits, _Alloc >::cend(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::compare(), std::basic_string< _CharT, _Traits, _Alloc >::empty(), std::basic_string< _CharT, _Traits, _Alloc >::end(), std::basic_string< _CharT, _Traits, _Alloc >::end(), std::basic_string< _CharT, _Traits, _Alloc >::length(), std::basic_string< _CharT, _Traits, _Alloc >::operator __sv_type(), std::basic_string< _CharT, _Traits, _Alloc >::operator[](), std::basic_string< _CharT, _Traits, _Alloc >::operator[](), std::basic_string< _CharT, _Traits, _Alloc >::pop_back(), and std::basic_string< _CharT, _Traits, _Alloc >::push_back().
starts_with() [1/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::starts_with (_CharT __x) const inline noexcept
Definition at line 3021 of file cow_string.h.
starts_with() [2/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::starts_with (basic_string_view< _CharT, _Traits > __x) const inline noexcept
Definition at line 3017 of file cow_string.h.
starts_with() [3/3]
template<typename _CharT , typename _Traits , typename _Alloc > bool std::basic_string< _CharT, _Traits, _Alloc >::starts_with (const _CharT * __x) const inline noexcept
Definition at line 3026 of file cow_string.h.
substr()
template<typename _CharT , typename _Traits , typename _Alloc > basic_string std::basic_string< _CharT, _Traits, _Alloc >::substr (size_type __pos = 0, size_type __n = npos) const inline
Get a substring.
Parameters
__pos Index of first character (default 0).
__n Number of characters in substring (default remainder).
Returns
The new string.
Exceptions
std::out_of_range If __pos > size().
Construct and return a new string using the __n characters starting at __pos. If the string is too short, use the remainder of the characters. If __pos is beyond the end of the string, out_of_range is thrown.
Definition at line 2752 of file cow_string.h.
References std::basic_string< _CharT, _Traits, _Alloc >::basic_string().
swap()
template<typename _CharT , typename _Traits , typename _Alloc > void std::basic_string< _CharT, _Traits, _Alloc >::swap (basic_string< _CharT, _Traits, _Alloc > & __s) noexcept
Swap contents with another string.
Parameters
__s String to swap with.
Exchanges the contents of this string with that of __s in constant time.
Definition at line 3512 of file cow_string.h.
Referenced by std::basic_string< _CharT, _Traits, _Alloc >::assign(), and std::basic_string< _CharT, _Traits, _Alloc >::operator=().
Member Data Documentation
npos
template<typename _CharT , typename _Traits , typename _Alloc > const basic_string< _CharT, _Traits, _Alloc >::size_type std::basic_string< _CharT, _Traits, _Alloc >::npos static
Value returned by various member functions when they fail.
Definition at line 330 of file cow_string.h.
The documentation for this class was generated from the following files:
cow_string.h
basic_string.tcc