libstdc++: std::chi_squared_distribution< _RealType > Class Template Reference
std::chi_squared_distribution< _RealType > Class Template Reference
Numerics » Random Number Generation » Random Number Distributions » Normal Distributions
#include <random>
Classes
struct param_type
Public Types
typedef _RealType result_type
Public Member Functions
chi_squared_distribution (_RealType __n)
chi_squared_distribution (const param_type &__p)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator >
void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng)
template<typename _ForwardIterator , typename _UniformRandomNumberGenerator >
void __generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
template<typename _UniformRandomNumberGenerator >
void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator >
void __generate (result_type *__f, result_type *__t, _UniformRandomNumberGenerator &__urng, const param_type &__p)
result_type max () const
result_type min () const
_RealType n () const
template<typename _UniformRandomNumberGenerator >
result_type operator() (_UniformRandomNumberGenerator &__urng)
template<typename _UniformRandomNumberGenerator >
result_type operator() (_UniformRandomNumberGenerator &__urng, const param_type &__p)
param_type param () const
void param (const param_type &__param)
void reset ()
Friends
template<typename _RealType1 , typename _CharT , typename _Traits >
std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const std::chi_squared_distribution< _RealType1 > &__x)
bool operator== (const chi_squared_distribution &__d1, const chi_squared_distribution &__d2)
template<typename _RealType1 , typename _CharT , typename _Traits >
std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > &__is, std::chi_squared_distribution< _RealType1 > &__x)
Detailed Description
template<typename _RealType = double>
class std::chi_squared_distribution< _RealType >
A chi_squared_distribution random number distribution.
The formula for the normal probability mass function is
Since
C++11
Definition at line 2710 of file random.h.
Member Typedef Documentation
result_type
template<typename _RealType = double> typedef _RealType std::chi_squared_distribution< _RealType >::result_type
The type of the range of the distribution.
Definition at line 2717 of file random.h.
Constructor & Destructor Documentation
chi_squared_distribution() [1/3]
template<typename _RealType = double> std::chi_squared_distribution< _RealType >::chi_squared_distribution () inline
Definition at line 2749 of file random.h.
chi_squared_distribution() [2/3]
template<typename _RealType = double> std::chi_squared_distribution< _RealType >::chi_squared_distribution (_RealType __n) inline explicit
Definition at line 2752 of file random.h.
chi_squared_distribution() [3/3]
template<typename _RealType = double> std::chi_squared_distribution< _RealType >::chi_squared_distribution (const param_type & __p) inline explicit
Definition at line 2757 of file random.h.
Member Function Documentation
__generate() [1/4]
template<typename _RealType = double> template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void std::chi_squared_distribution< _RealType >::__generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator & __urng) inline
Definition at line 2830 of file random.h.
__generate() [2/4]
template<typename _RealType = double> template<typename _ForwardIterator , typename _UniformRandomNumberGenerator > void std::chi_squared_distribution< _RealType >::__generate (_ForwardIterator __f, _ForwardIterator __t, _UniformRandomNumberGenerator & __urng, const param_type & __p) inline
Definition at line 2837 of file random.h.
__generate() [3/4]
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > void std::chi_squared_distribution< _RealType >::__generate (result_type * __f, result_type * __t, _UniformRandomNumberGenerator & __urng) inline
Definition at line 2846 of file random.h.
__generate() [4/4]
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > void std::chi_squared_distribution< _RealType >::__generate (result_type * __f, result_type * __t, _UniformRandomNumberGenerator & __urng, const param_type & __p) inline
Definition at line 2852 of file random.h.
max()
template<typename _RealType = double> result_type std::chi_squared_distribution< _RealType >::max () const inline
Returns the least upper bound value of the distribution.
Definition at line 2806 of file random.h.
References std::numeric_limits< _Tp >::max().
min()
template<typename _RealType = double> result_type std::chi_squared_distribution< _RealType >::min () const inline
Returns the greatest lower bound value of the distribution.
Definition at line 2799 of file random.h.
n()
template<typename _RealType = double> _RealType std::chi_squared_distribution< _RealType >::n () const inline
Definition at line 2772 of file random.h.
operator()() [1/2]
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::chi_squared_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng) inline
Generating functions.
Definition at line 2814 of file random.h.
operator()() [2/2]
template<typename _RealType = double> template<typename _UniformRandomNumberGenerator > result_type std::chi_squared_distribution< _RealType >::operator() (_UniformRandomNumberGenerator & __urng, const param_type & __p) inline
Definition at line 2819 of file random.h.
param() [1/2]
template<typename _RealType = double> param_type std::chi_squared_distribution< _RealType >::param () const inline
Returns the parameter set of the distribution.
Definition at line 2779 of file random.h.
param() [2/2]
template<typename _RealType = double> void std::chi_squared_distribution< _RealType >::param (const param_type & __param) inline
Sets the parameter set of the distribution.
Parameters
__param The new parameter set of the distribution.
Definition at line 2787 of file random.h.
References std::gamma_distribution< _RealType >::param().
reset()
template<typename _RealType = double> void std::chi_squared_distribution< _RealType >::reset () inline
Resets the distribution state.
Definition at line 2765 of file random.h.
References std::gamma_distribution< _RealType >::reset().
Friends And Related Symbol Documentation
operator<<
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_ostream< _CharT, _Traits > & operator<< (std::basic_ostream< _CharT, _Traits > & __os, const std::chi_squared_distribution< _RealType1 > & __x) friend
Inserts a chi_squared_distribution random number distribution __x into the output stream __os.
Parameters
__os An output stream.
__x A chi_squared_distribution random number distribution.
Returns
The output stream with the state of __x inserted or in an error state.
operator==
template<typename _RealType = double> bool operator== (const chi_squared_distribution< _RealType > & __d1, const chi_squared_distribution< _RealType > & __d2) friend
Return true if two Chi-squared distributions have the same parameters and the sequences that would be generated are equal.
Definition at line 2865 of file random.h.
operator>>
template<typename _RealType = double> template<typename _RealType1 , typename _CharT , typename _Traits > std::basic_istream< _CharT, _Traits > & operator>> (std::basic_istream< _CharT, _Traits > & __is, std::chi_squared_distribution< _RealType1 > & __x) friend
Extracts a chi_squared_distribution random number distribution __x from the input stream __is.
Parameters
__is An input stream.
__x A chi_squared_distribution random number generator engine.
Returns
The input stream with __x extracted or in an error state.
The documentation for this class was generated from the following files:
random.h
bits/random.tcc