libstdc++: __gnu_parallel::multiway_mergesort_tag Struct Reference
__gnu_parallel::multiway_mergesort_tag Struct Reference
#include <tags.h>
Public Member Functions
multiway_mergesort_tag (_ThreadIndex __num_threads)
_ThreadIndex __get_num_threads ()
void set_num_threads (_ThreadIndex __num_threads)
Detailed Description
Forces parallel sorting using multiway mergesort at compile time.
Definition at line 128 of file tags.h.
Constructor & Destructor Documentation
multiway_mergesort_tag() [1/2]
__gnu_parallel::multiway_mergesort_tag::multiway_mergesort_tag () inline
Definition at line 130 of file tags.h.
multiway_mergesort_tag() [2/2]
__gnu_parallel::multiway_mergesort_tag::multiway_mergesort_tag (_ThreadIndex __num_threads) inline
Definition at line 131 of file tags.h.
Member Function Documentation
__get_num_threads()
_ThreadIndex __gnu_parallel::parallel_tag::__get_num_threads () inline inherited
Find out desired number of threads.
Returns
Desired number of threads.
Definition at line 63 of file tags.h.
Referenced by __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort(), __gnu_parallel::__parallel_sort(), and __gnu_parallel::__parallel_sort().
set_num_threads()
void __gnu_parallel::parallel_tag::set_num_threads (_ThreadIndex __num_threads) inline inherited
Set the desired number of threads.
Parameters
__num_threads Desired number of threads.
Definition at line 73 of file tags.h.
The documentation for this struct was generated from the following file:
tags.h