#!/bin/sh
# autopkgtest check: Build and run a simple program against libc, to verify
# basic compile-time and run-time linking functionality.
#
# (C) 2012 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>

set -e

BV=$(sed '/^Depends: gcc-\([0-9.]\+\).*/!d;s//\1/;q' debian/tests/control)
CC=gcc-$BV

cd "$AUTOPKGTEST_TMP"
cat <<EOF > libctest.c
#include <string.h>
#include <assert.h>

int main()
{
    assert (1 > 0);
    assert (strcmp ("hello", "hello") == 0);
    return 0;
}
EOF

$CC -o libctest libctest.c
echo "build: OK"
[ -x libctest ]
./libctest
echo "run: OK"
